### ISSUE TITLE
WYSIWYG Editor for Application Note

### ISSUE THREAD

**Issue by AyelGoth** [nextcloud/notes#111]
Ability to add a WYSIWYG editor such as JCE or TinyMCE, to edit notes with tools more fully and intuitively.

**Comment by Henni** [comment]
See https://github.com/brantje/ownnote for current work on this.

**Comment by korelstar** [comment]
@Henni What's your opinion regarding the idea to merge the existing notes apps? (See https://github.com/Fmstrat/ownnote/pull/329#issuecomment-267615429 and https://github.com/brantje/ownnote/issues/5#issuecomment-312513842). Of course, it would be hard to decide into which direction the merge should go ...

**Comment by Henni** [comment]
@korelstar still undecided.
I doubt that it would be easy to support all clients after a merge, but on the other hand we probably don't want to maintain two notes apps...

**Comment by brantje** [comment]
Well, if the API structure doesn't differ much it would be possible to serve the Notes API from within the NextNotes app.

**Comment by AyelGoth** [comment]
I think it's a good idea to merge all notes applications into one if the NextCloud API and ownCloud allow it. If you do not allow it, then the remedy would be to bridge all APIs.

**Comment by brantje** [comment]
We will have problems with [routes](https://github.com/brantje/ownnote/issues/5#issuecomment-312556493)

**Comment by korelstar** [comment]
@Henni (cc @nextcloud/notes)
Then let's look if the main goals of these apps are compatible. I tried to list the differing goals, that have been realized for now.

**Nextcloud Notes**
- simple UI ("distraction-free", few clicks, ...; escpellialy forced by @jancborchardt and @Henni)
- markups using Markdown
- files in hierarchical folders as backend (forced by our users, who want to sync using WebDAV)
- 3rd-party API which takes into account the special requirements for mobile environments and which provides concurrent/transactional access (forced by @korelstar, the last part is not fully realized yet)
- deep cooperation to an Android client (https://github.com/stefan-niedermann/nextcloud-notes)

**ownNote/Nextnote**
- WYSIWYG editor (forced by their users)
- markups using HTML and embedded images (import from Evernote should be possible)
- database backend
- sharing notes

Did I miss anything?

**Comment by e-alfred** [comment]
@korelstar There is an android app for ownNote too: https://github.com/Fmstrat/ownnote-mobile

OwnNote also saves to either both filesystem and database or database only.

**Comment by korelstar** [comment]
Thanks, I've updated the list. I think I did not list the Android client, since I read [somewhere](https://github.com/brantje/ownnote/issues/5#issuecomment-313486211), that a comepletely new app should be developed. But I added it now.

**Comment by jancborchardt** [comment]
Yep - I suggest everyone to check out the great iA Writer app which the Notes app also took inspiration from: https://ia.net/writer/

Notes is all about focus on writing and quick loading and painless sync.
If you check how iA writer for example includes images or even other documents, it's pretty good - you simply write the filebame in the text preceded by a slash:

> /image.png
> /headersection.txt

We could do it similarly, just like with the inline Markdown: As soon as you put in a slash and write after it, you could get images or files in the same folder recommended for autocompletion.
And if therr is an image name written in that fashion, the image could be shown below directly.

**Comment by putt1ck** [comment]
So,long as it supports select-copy middleclick-paste I'm happy 👍

**Comment by korelstar** [comment]
So, we had some time to think about the main goals of both apps. What is the conclusion when comparing them? Are they compatible and a merge would be reasonable or will we have forks again soon or later (see https://github.com/brantje/nextnote/issues/5#issuecomment-313627187)?

**Comment by ThomasDaheim** [comment]
My 2 cents: I think it would be possible to use a common server backend. We would only need to sync on how we support groups, tags, ... At least an option using files and folders only, so that offline work on the notes is possible would also be good.

With that in place anyone could come up with a front end for his/her favorite file format and editor. A common/generic editor seems to be impossible to achieve for me (or it would be a real monster).

**Comment by jancborchardt** [comment]
> With that in place anyone could come up with a front end for his/her favorite file format and editor.

That usually doesn’t happen though, and is also not really something we want. We should encourage working together on one (or maybe two) good apps. We had the same issue in the past with Calendar and Contacts and the infamous Calendar+ and Contacts+ apps which ended up unmaintained.

The key is that the current notes app already enables that: You can use whichever app you like, even the files_texteditor, since it just uses plain text files. And the default Notes app gives a nice, non-distracting, well-designed interface.

**Comment by eemantsal** [comment]
Hi all.

I come from here https://github.com/stefan-niedermann/nextcloud-notes/issues/272 by kind indication of @stefan-niedermann 

My suggestion was, too, adding an **optional** WYSIWYG interface because I think that the majority of common mobile devices users don't understand why do they need to learn a markup language instead just selecting some text and tappin some button to format, like they accustom to do in their text processors or other mobile notes apps; and see all these "*s", "#s" "===s", etc like "yet another geeky and obscure FLOSS things". It would be also handier and quicker in many cases (doing a couple of quick modifications here and there) even for, more or less, "Markdown literate users".

I want to state clear that I'm not proposing switching from Markdown format for the notes to HTML at all. I'm convinced that besides the advantages of MD's simplicity and the possibility to edit MD files in almost any digital text write capable thing, MD is potent enough for the needs of at least 95% of users, that only want some basic text formatting, media, principally images, embedding and perhaps chechkboxes for tasks and such. I don't even believe that the vast majority does ever use tables nor code text formatting, which are already present in the MD specifications.

So there's no need to complicate things with HTML, pease don't get me wrong. I suggest **only an interface improvement** that might make the Nextcloud notes much more accessible to common users and handier in some occasions for those who already know how to compose texts in Markdown. A more graphical interface so users can edit their notes without needing to learm Markdown syntax and can see the results inmediately on a single view, instead of having to switch from a code view to the definitive view and switch back to the code view to continue editing, and then swit...
This should be elegible by the users, maybe with just a button that enables/disables WYSIWYG or some switch in the app's settings... I don't know, I'm not a developer; I'm sure you can think of much better implementations than I.

As I said in the aforesaid conversation, there are a lot of web apps that work this way. See, for example, [Telegra.ph](http://telegra.ph), [Pen Editor](https://github.com/sofish/pen) or [this plugin for MediumEditor](http://linkesch.com/medium-editor-insert-plugin/). All of them permit the users to edit the text in a WYSIWYG mode and don't clutter at all the interface.

I hope I've contributed to the discussion with some valid point.
Best regards.

**Comment by eemantsal** [comment]
@jancborchardt 

That slash thing you propose is a really nice idea, handier than typing that ![Alt text](url), but I don't think having all the media files mixed up in the same folder than .md files is such a good idea. One may need to do some file browsing in his noes folders and that mix would be a mess.
There's a nice MD editor for the desktop, [Qownnotes](https://github.com/pbek/QOwnNotes) that crates a folder named `Media` inside the corresponding notes folder, and then it stores all the multimedia content there. So, when you browse through your notes folders yo see all your md files, adn if want to open or edit any, there you have them clearly at your sight; and then you have said `Media` folder with all the pictures and such.

Would it be possible to type `/media/File_you_want_to_embed`, or even better, make the app interpreta that `/File_you_want_to_embed` points to `/media/File_you_want_to_embed` so the user doesn't have to mess with the "/media" part?

**Comment by jancborchardt** [comment]
@eemantsal maybe it’s best to open a separate specific issue about this since here it’s closed and so long already. :) Mind doing that, maybe including the reference to iA writer?

**Comment by eemantsal** [comment]
@jancborchardt 

Sure. I came to this thread because Hr. Niedermann pointed me here. I didn't notice this issue was closed, sorry.
I'll almost totally copy-paste what I've posted here in a new issue. ;)

**Comment by eemantsal** [comment]
@jancborchardt, I don't know how could I make a reference to that nice feature of iA Writer for embedding media files because my post was about a WYSIWYG interface, not about improving the plain text editor. I do agree with what you said, it's a good idea, but it's a raher unrelated topic, I think. :-|
Since I feel like about opening a new issue to suggest image support for both the mobile and web notes app I think I could mention it there.
