### ISSUE TITLE
Unable to connect to server with android client (v0.11), Error E/S

### ISSUE THREAD

**Issue by gringo1er** [nextcloud/notes#112]
Hello
In order to explain the context, I have 2 nextcloud servers, one is the backup of the other.
The main one is a ubuntu 17.04 PHP7 MySQL Apache2 server. SSL is active, with official paid SSL certificates (not a let's encrypt) provided by our domain name provider, and certified by Comodo.

Nextcloud is fully operative. But when I try to access to the notes with a client, I have a "Détail de connexion incorrect erreur d'E/S" issue.
When I replace the server by the backup (same SSL certificates, but on a Synology platform), it works.

So my question: is there any 3rd party tool to be installed on Ubuntu? Is there anything to add / activate?

Thank you

**Comment by korelstar** [comment]
No, there are no special requirements on the OS side. Please check the nextcloud.log on the server.

Am 8. Juli 2017 09:43:30 MESZ schrieb gringo1er <notifications@github.com>:
>Hello
>In order to explain the context, I have 2 nextcloud servers, one is the
>backup of the other.
>The main one is a ubuntu 17.04 PHP7 MySQL Apache2 server. SSL is
>active, with official paid SSL certificates (not a let's encrypt)
>provided by our domain name provider, and certified by Comodo.
>
>Nextcloud is fully operative. But when I try to access to the notes
>with a client, I have a "Détail de connexion incorrect erreur d'E/S"
>issue.
>When I replace the server by the backup (same SSL certificates, but on
>a Synology platform), it works.
>
>So my question: is there any 3rd party tool to be installed on Ubuntu?
>Is there anything to add / activate?
>
>Thank you

**Comment by gringo1er** [comment]
I have that type of logs

1 | 2 | 3 | 4
-- | -- | -- | --
Error | index | OCP\Lock\LockedException: "Notes/Nouvelle note.txt" is locked | 2017-07-07T20:05:46+0200
Error | index | OCP\Files\NotFoundException: | 2017-07-07T19:45:21+0200
Warning | core | Login failed: 'LOGIN' (Remote IP: '192.168.0.254') | 2017-07-07T19:15:24+0200
Warning | core | Login failed: 'LOGIN' (Remote IP: '192.168.0.254')

The remote IP is the router IP (for internet access).

**Comment by korelstar** [comment]
Which ones happen if you try to synchronize using the app? Do they happen every time? Which version of the server and android app do you use? ...

Please try to investigate the error source by understanding the errors in the log and think about the listed file (is there something special about that? ...)

**Comment by fernandocollova** [comment]
@gringo1er Are the 2 servers running the same Nextcloud version? Because I think I'm having the same issue as you, and I think they started after I updated to V12.0.1. To be perfectly clear, I'm not 100% sure about that, because I didn't open the app the same date I upgraded, but I don't remember updating the android app or anything else, so maybe it was that.

For some info about my system setup in case it helps debugging, I'm currently running the nextcloud:12.0-apache docker image, with really minimal modifications (changed server name, added cron in the background) behind an Apache https reverse proxy with a letsencrypt cert. The app's version is also v0.11.0

Also, apart from the startup notification logs, I have no logs since I restarted the server 5 days ago (IDK if that's normal or not)

Here is also the system info that the admin panel gives me in case it helps:

PHP
Version: 7.1.8
Memory Limit: 536870912
Max Execution Time: 3600
Upload max size: 511 MB

Database
Type: pgsql
Version: PostgreSQL 9.5.7 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1), 64-bit
Size: 53.7 MB

And, a [link](https://fernandocollova.com/nextcloud/index.php/s/k8BwZgtlAZNW33G) to a screenshot if the error toast the app makes.

Finally, apart from the problems with the notes app, I can sync calendars, contacts, tasks, files, share public links.... So I think everything works fine.

**Comment by gringo1er** [comment]
Hello.
Thank you for your help.

Hereafter you can find the detail of the configuration:
PHP 7.0.22-0ubuntu0.17.04.1
mysql  Ver 14.14 Distrib 5.7.19
Apache 2.4

The SSL certificate is an official (paid) one, linked with the domain name (paid, also). Everything works fine (web access, with a green flag for security check on Chrome and Firefox browser), also nextcloud sync client on PC and android. Same thing for caldav and carddav clients for android.

Everything is working, except Nextcloud note client for android.

A DNS problem? the hosts file links 127.0.1.1 to the good domain name.

But I have an idea.
When I check the apache configuration, I have a message:
 Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot

It seems to be a classic alert on that apache version, even if I don't know yet how to solve it...

An idea, maybe?

**Comment by gringo1er** [comment]
The issue seems to be a SSL problem.

Without the "s" on http, its works  (with the security alert, of course. With the "s", I obtain the E/S error.

If I insist with my phone, I obtain the joined java message
![20170815_135513](https://user-images.githubusercontent.com/9809622/29317852-20a231c8-81ce-11e7-98f4-4ac328d062a0.png)

**Comment by gringo1er** [comment]
Solved!
Due to the fact it's seemed to be a SSL problem, I have checked my server with digicert.com
And I obtained an error with the intermediate certificate (for the trust certification authority).

After a quick look on my default-ssl.conf, I saw that I forgot a "#" at the beginning of the path for that intermediate certificate.

A quick apache2 service restart, and everything is fine. It works!!

Now I can close the issue...

Thanx for all...
