### ISSUE TITLE
Markdown issue

### ISSUE THREAD

**Issue by Larsene** [nextcloud/notes#158]
Hi, i first want to thanks for this wonderful simple app !

Is it normal that the code characters (**, __, `) are visible after using them ? Usually, in Markdown syntax, they disappear to user after using them. Perhaps could you gray them for better reading ?

the * for bullet list is also not replaced with a bullet.

Links elements doesn't produce real clickable links

Anyway, Many thanks

**Comment by gorn** [comment]
This only happens when you have spaces before * (star) ... the app prefers that star is at the beginning of the line. If it is not, it is strangely accepted as bullet AS WELL AS the star itself, which is somehow confusing.

**Comment by jancborchardt** [comment]
Just to clarify, yes it is intended that the characters are still visible after using them. This is not a WYSIWYG editor, but a simple plaintext editor heavily inspired by [iA Writer](https://ia.net/writer). :)

Of course when you use asterisks (or dashes) at the beginning of a line, it should create a list (which happens) and the links should be clickable. → Let’s switch to the more specific issue at https://github.com/nextcloud/notes/issues/173

When you encounter more issues, please open separate issues for each problem, otherwise it’s hard to track. Thanks!
