### ISSUE TITLE
Undo dialog timeout + orientation bug 

### ISSUE THREAD

**Issue by woodcarver76** [nextcloud/notes#178]
The Undo dialog that appears after deleting a note is visible for a very short time, and can be hard to reach in time before you realise what you just did. 

Also, when changing orientation, the dialog disappears immediately. This created a problem: While scrolling through my list of notes, I accidentally tilted the phone a little so it changed to landscape mode briefly, interpreted one of my upward swipes as a side swipe, deleted a random note (which one?) and immediately switched back to portrait. Absurdly unlucky, I know :)

**Comment by stefan-niedermann** [comment]
Hi,

i think, you are referring to the android app. the repo is here:

https://github.com/stefan-niedermann/nextcloud-notes

There was already an issue for the orientation change problem, but it shoud have been fixed in the meantime (https://github.com/stefan-niedermann/nextcloud-notes/issues/301)

Please make sure, you are using the very latest version (0.13.1). If the problem still occurs, feel free to open a new issue at the mentioned android repository.

Regarding to the timeout of the Undo-operation: also open a separate issue at thr android repo please.

Regards

**Comment by woodcarver76** [comment]
Thanks, I will do that!

Den tors 22 mars 2018 09:06Niedermann IT-Dienstleistungen <
notifications@github.com> skrev:
