### ISSUE TITLE
Use SimpleMDE Toolbar?

### ISSUE THREAD

**Issue by joewashear007** [nextcloud/notes#193]
I was reading through the issues and it seems that a lot of the features people want (#23,  #71, #115, #138, #158 - Some things can only be used in the "view" view) are already built into the SimpleMDE editor with the toolbar. Other than having to include font-awesome as a dependency for a few icons, is there any reason that you wouldn't want to use that? 

This is then more personal style, but they status bar could be done with the SimpleMDE status bar and the full screen button is already there.

But I like the look of the tool bar:
![image](https://user-images.githubusercontent.com/3577785/39224977-f9fa1cdc-4817-11e8-94a6-ec25380f89d8.png)

**Comment by stefan-niedermann** [comment]
Dear @joewashear007,

i am not the maintainer of this project, but from my point of view, this is not the focus of this project to format text but to *write* text. therefore the priority belongs to a destraction free writing experience instead which means that cluttering the UI would be bad because formatting is not the primary fuction of this app.

I also think this is the key difference to the NextNotes project, which provides a more powerful way to format notes and comes with toolbars and so on. Did you have a look at it?

**Comment by alexanderdd** [comment]
Hey everyone,
Thanks for posting this.

@Henni and @LukasReschke could you please comment which path you want the app to go? Pure writing app, or is a toolbar ok?

IMHO, I would like to see the SimpleMDE toolbar in the notes app. My reasons are:
* NextNotes is unmaintained and "should not be used in production": https://github.com/janis91/nextnotes/blob/master/README.md
* notes will be the first choice for the regular home user, who will expect simple formatting options visible on the screen from a note-taking app (having to know the MD formatting tricks is a barrier for those users)
* speaking of distraction-free: I actually find the #'s and **'s a little distracting. I know I can switch to the "view" view, but that kills the usability for me. It's like writing html or latex, where you always have this extra step. A fast note-taking app should be wysiwyg in my opinion. But thats a off-topic.

Also, this dicussion may be relevant:
https://help.nextcloud.com/t/what-will-be-the-default-note-app/424/28

What do you think?

**Comment by alexanderdd** [comment]
Maybe also relevant: https://github.com/nextcloud/notes/issues/183

**Comment by jancborchardt** [comment]
As said, the aim of this app is to allow for simple writing and note-taking, distraction-free. We can add things which make it easier to add the markdown lists and bolding, and even images etc – not as a permanent toolbar but only visible in context, like with Medium:
![](https://cdn-images-1.medium.com/max/1600/1*GwPgFezPFHMKqN1EXBlhzg.png)

Just because NextNotes is unmaintained, it doesn’t change the trajectory of this, much longer existent app. It is also sustainable because it is so simple. Also see my comment at 
https://github.com/nextcloud/notes/issues/138#issuecomment-386765207

Hence I’ll close this since we will not go with a toolbar. If someone wants to pick up the context-based formatting popup, you are very welcome to! :) Just opened an issue for it at https://github.com/nextcloud/notes/issues/200
