### ISSUE TITLE
Store notes in CalDAV/VJOURNAL

### ISSUE THREAD

**Issue by bestouff** [nextcloud/notes#197]
Hi,

Some PIM apps (e.g. Evolution) use CalDAV to store their notes (in a VJOURNAL entry). This works quite well with Nextcloud, after running something like `update oc_calendars set components='VEVENT,VTODO,VJOURNAL' where id in (...)`. It'd be nice to be able to see/edit/create these notes with this app.

**Comment by stefan-niedermann** [comment]
I disagree, i think this makes more sense for apps like tasks/todos - a use case the notes app should not cover imho because there are better alternatives for more powerful management.

**Comment by stefan-niedermann** [comment]
You forget many users who only use the default file sync client to synchronize their stuff and write their notes with a markdown editor of their choice. Switching the backend would be an backwards incompatible breaking change, that requires users to even more think about how to manage their simple notes, which tools, which protocols and so on.

It should simply work, ideally without additional software (optionally with, so advanced users can take benefits).

That's the reason i do not support leaving the filebased approach.

**Comment by bestouff** [comment]
The idea would be to offer another backend for the notes, for those who want to be able to read/write their already existing notes from their PIM, not to eliminate the already existing files backend.

**Comment by jancborchardt** [comment]
Yeah, as @stefan-niedermann mentions, moving away from file-based is not something we will do – but I guess that’s not what you request @bestouff :)

The biggest issue I see here is the tradeoff of investment and usefulness: This so far has been the first time we had this request, so I assume the need is quite low. CalDAV is used for Calendar and Tasks, but doesn’t seem so popular for Notes. Also, there’s so many clients for WebDAV or Nextcloud already so you can sync your notes very easily, and even edit it with whichever app you want. With CalDAV, there’s a much narrower spectrum – as you mention Evolution and KOrganizer.

So the time involved in developing and maintaining this just so that it integrates a tiny bit better into these systems is not really worth it in my opinion – sorry. Especially as there’s already much better integration on a direct file system level.

**Comment by jancborchardt** [comment]
However @bestouff if you (or someone else) are up for developing and (more importantly) _maintaining_ an optional CalDAV backend integration for Notes, you are very welcome to do so! :)

Just please understand that with our limited resources and the limited demand it’s not something we can commit to – because if we can’t do it well we’d rather not do it at all.

**Comment by Woren** [comment]
I just want to add that very popular eM Client also added Notes support with CalDAV in the newest [version 8](https://www.emclient.com/blog/em-client-8-beta-is-finally-here-340).

**Comment by patrickunterwegs** [comment]
Hi, I would like to open up this topic again. I have developed together with bitfire (DAVx5) an app that allows you to synchronise Journals, Notes and Tasks (VJOURNAL and VTODO compliant): jtx Board. The idea behind this app was to actually increase the use of open standards and espcecially also to promote the VJOURNAL definition. 
Is there a chance to get this topic picked up again?

Regarding the discussion above by @stefan-niedermann , I don't see any disadvantages if people use markdown. Even if the an editor does not support markdown, I'd say it is one of the basic ideas that the text stays readible. Also jtx Board would basically interpret markdown tags even though the editor does not explicitely offer formatting options.

So @jancborchardt , maybe it's worth reopening this issue? Or I could also start a new discussion ;-)


More info about the app: [https://jtx.techbee.at/](https://jtx.techbee.at/) 
It's open source by the way!

**Comment by korelstar** [comment]
Hey @patrickunterwegs , the approach is interesting. However, one of the main architecture decisions of this app is to use files as backend in order to be compatible with file syncing and as much editors as possible. Therefore, we will not change the backend to CalDAV.

Another suggestion was to add CalDAV as additional backend. To be clear: I will not create and maintain such a backend, since I have not enough free time for this. But even if somebody else would do this, I'm unsure if this approach would be compatible to this app. E.g., the notes app uses numeric ids as unique identifier, but I doubt this would be possible with CalDAV. Furthermore, I fear that it will be hard for users to understand the meanings of different backends - but they would necessarily need to chose one (or do you suggest to mix notes from different backends?). And what about our public API for third-party apps? Should we provide notes from CalDAV to them, too? Or should they implement CalDAV by themselves? All in all, the approach of adding an additional backend to the notes app doesn't feel well.
