### ISSUE TITLE
Context-based formatting popover

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#200]
To keep in line with our distraction-free design, but also to make the formatting easier to use, we should introduce a context-based formatting popover similar to what Medium.com has. Whenever you select text, the formatting options show:
![](https://cdn-images-1.medium.com/max/1600/1*GwPgFezPFHMKqN1EXBlhzg.png)

Then when you bold the text, it would insert the `**asterisks**` around the selected word, or for links it would `[insert the link tag and focus it on the url part](https://…)`.

cc @nextcloud/notes

**Comment by exekutive** [comment]
What normal layperson would want to see a bunch of asterixes in their note?? How about implementing ACTUAL FORMATTING like bolt type and bullets so that notes written for personal use look nice and are actually READABLE. You complain that people try to write their own apps, rather than changing this one, but you refuse to change the scope. Markdown is for nerds only and guarantees that this app will never be widely adopted. You don't have to make it a word processor. Just basic stuff like bold, bullets, maybe italic, and 3 sizes. 

The name of the app is NOTES, so focus on that instead of making it a 1337 text editor.

**Comment by putt1ck** [comment]
@exekutive you mean not text though. To support text formatting you have to have a save format that is more than text. Something that tells the UI to render this **word** in bold and that this:
*  should be a be a bullet point line.

Markdown is just a way of doing this. How it looks when you open it is down to the tool you use to open it. Even junior 1337 types can write markdown as they type, but few would normally consume a markdown file in "raw", just as they wouldn't an RTF or HTML one.

**Comment by jancborchardt** [comment]
@exekutive it's all done in steps, and development only happens when people work on it. Your tone serves only to demotivate people, so please read comments again before you post.

**Comment by exekutive** [comment]
@ putt1ck Store it as whatever you like, but 99% people of people aren't going to learn markdown just so they can take down notes. You are exactly right ... how it looks is down to the tool. This app IS a tool so why not make it user friendly??

@jancborchardt You are shutting down topics suggesting how to improve usability, based on your own narrow vision. THAT is demotivating.

**Comment by putt1ck** [comment]
There will be a **WYSIWYG**. Just like on Github.

**Comment by stefan-niedermann** [comment]
@exekutive great to hear, we all have the same target: enhancing the user experience of this app. If you want to start contributing, you can take one of the issues labled with "Good first issue" and simply provide a Pull Request.

You might or might not know that we all are working in our free time receiving no money for it. Therefore i would suggest to be more polite and respectful when you speak about the work of other people. If it does not fit your needs, i am sure you will be able to find alternatives. In fact, many thousand people are known to be happy with the app.

Since we have very limited ressources, it is important to focus on small steps to improve the app - therefore it would be great if you could start providing Pull Requests as mentioned above.

And at this point i want to stop this pointless conversation. Please keep your focus on the issue and how we can solve it. It will definitely be a great enhancement for alle users. :rocket:

**Comment by exekutive** [comment]
@ putt1ck 
Please correct me if I'm wrong, but there is only WYSIWYG viewing, not writing.

@ stefan
I don't think I disrespected anybody. Everything I said was true. I'm disappointed that you considered this debate pointless. When you make things for other people to use, and invite feedback, then try not to take opposing opinions personally. Honesty is something we need more of.

Maybe someday my skills will be good enough to contribute some code, but for now all I can provide is end user feedback. 

Anyway, there have been no alternatives (jancborchardt denouncing them doesn't help) until now. The new NextNotes is more practical to me so I switched to that.

Cheers. :)

**Comment by jancborchardt** [comment]
Since you switched to Nextnotes anyway, I’ll hide your comments here. @exekutive there is a difference between honesty and tone – uppercase words and double questionmarks are not nice tone.

**Comment by exekutive** [comment]
I apologize for that. I meant to emphasize, not shout. I'll work on my etiquette.

**Comment by jancborchardt** [comment]
There’s "a renderless rich-text editor for Vue.js" called [tiptap](https://tiptap.scrumpy.io/menu-bubble) which does what I described with the menu bubble:
![tiptap bubble](https://user-images.githubusercontent.com/925062/50029333-b514ae00-fff2-11e8-9057-f0a390f11ee1.png)
