### ISSUE TITLE
Error with shared Notes-Folder

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/notes#256]
In the Nextcloud Instance ist the folder "Notes" Shared with a group.
I get the following error:

"Verschlüsselungsfehler: (New note.txt) Encryption library: Decryption (symmetric) of content failed: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length"

**Comment by korelstar** [comment]
I tried to reproduce this. I did the following steps:

1. activate server-side encryption
2. create users "test1" and "test2"
3. login as "test1"
4. create some notes
5. share folder "Notes" with "test2"
6. logout
7. login as "test2"
8. open notes app and see the notes from step 4.
9. open any note and read and/or write

Hence, I think sharing of encrypted notes should work -- in general.

Please
- give more information about used versions (Nextcloud server, notes app, ...),
- give more information about the configuration of your Nextcloud server (encryption, external storages, ...),
- give a detailed step-by-step description on what to do in order to reproduce the problem,
- check if you can read the notes files using the Nextcloud files app.

**Comment by Schneehexe** [comment]
I'am so sorry.
The mistake happened, while I used the "Impersonate" function in Nextcloud Userlist.
If I logon the regular way, it works fine!

Thanks of course.
