### ISSUE TITLE
Fatal Error when creating new Note directory

### ISSUE THREAD

**Issue by Wizlonex** [nextcloud/notes#286]
How to re-create:

Goto Notes App in Nextcloud (Version 15.0.0.0).  Select a note (called 'Readjustment Therapy', below) and change the Note label from uncategorized to a new label that does not exist.

Result:
Results in error notification in the browser as a 'toaster-style' message questioning whether the directory has write-access.   The Note IS successfully relabelled, but the error message is shown and the following log entry pops up every time:

**Formatted Nextcloud Log Entry**:
[notes] Fatal: Moving note 311101 (Readjustment therapy) to the desired target has failed with a OCP\Lock\LockedException: "Notes/Readjustment therapy.txt" is locked

PUT /index.php/apps/notes/notes/311101/category
from 192.168.1.21 by username at 2018-12-28T07:52:13+00:00

**Raw Log Output**:
{"reqId":"7Wem3ngTduCoZjULZl0l","level":4,"time":"2018-12-28T07:52:13+00:00","remoteAddr":"192.168.1.21","user":"username","app":"notes","method":"PUT","url":"/index.php/apps/notes/notes/311101/category","message":"Moving note 311101 (Readjustment therapy) to the desired target has failed with a OCP\\Lock\\LockedException: \"Notes/Readjustment therapy.txt\" is locked","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","version":"15.0.0.10","id":"5c25d63fe3eb8"}

Not sure if I am the only one to experience this, but I thought I'd post it in case it's helpful.

System: Ubuntu 16.04 (LXD containerized) / Apache2 / php 7.2.  I'll be happy to try to provide additional information if this is not an isolated instance.  THANK YOU.

**Comment by korelstar** [comment]
Thanks for reporting this issue. We hadn't any reports on such an issue, yet.

`LockedException` means that the note's file is locked, e.g. by another Nextcloud app, the Nextcloud server core or a sync client. Please ensure, that you have exclusive access to that file (i.e. disable background-jobs like file synchronization and close other browser windows).

Please answer the following questions in order to analyze the problem in more detail:

- Does this only happen for that specific note or for all notes?
- Does this only happen if you change the category or also if you change the note's content?
- Does this only happen if you change the category to a non-existent value or also if you use an existing category?
- Does this only happen in specific situations?
- Does this only happen for specific category values? Which category do you want to set? Are there any special chars in it?
- Which version of the notes app do you use?
- Any special configuration of Nextcloud?

**Comment by korelstar** [comment]
Any news on this?

**Comment by Wizlonex** [comment]
My apologies for the slow response.

The error stopped occuring after I reset a Nextcloud client sync app on my Windows computer, and it has failed to return.  I think this was a bizarre case of being uniquely system specific, even though it affected multiple instances if Nextcloud that I have on my network.  Please suspend this with no further action needed until/unless someone else (or me) provides an update.

Thank you for your excellent Note app, and your maintenance diligence. 

V/R

**Comment by korelstar** [comment]
Okay, thanks for the feedback. I close this issue for now, we can re-open it if the problem re-occurs.
