### ISSUE TITLE
Ship own version of marked

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/notes#292]
We need to bundle marked into files_texteditor as the server shipped one it is deprecated with NC16.

Usage in notes:
https://github.com/nextcloud/notes/blob/34460518b29148d01132482ef9ecc2cbb8bb07db/js/vendor/simplemde/src/js/simplemde.js#L14

Deprecation has been discussed in https://github.com/nextcloud/server/pull/13474#issuecomment-453082823

**Comment by korelstar** [comment]
Thanks for the hint, but I don't think that this app uses `marked` from the server core. Instead of the linked code above (source of simplemde), we are loading the minified (release) version:

https://github.com/nextcloud/notes/blob/master/templates/main.php#L14

As far as I can see, that version already includes `marked`.

Can somebody confirm this, please?

**Comment by korelstar** [comment]
Never mind and thanks anyway :-)
