### ISSUE TITLE
Sort by Title

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/notes#298]
Hey,

would it be possible to implement a function for sorting notes by Title?

Best Regards

**Comment by korelstar** [comment]
The app has two type of notes lists:

1. All notes, sorted by last modified date (default view for quickly finding recent notes)
2. Notes in a specific category, sorted by title (stable view to find a known note at the same position again)

So, yes: we have already sorting by title. You just have to select a category.

I think it's a good compromise between UI complexity and customization. Do you think we should change this?

**Comment by Iowaba** [comment]
May I join this dissociation? It would be good if you could choose the order (A-Z or Z-A) in the categories. Because I would like to take a part of my notes also by date of creation, in the sense of a diary. Since this sorting does not exist, I could start the first line of my notes with YYYY.MM.DD. If I wanted the latest note in the first place, I would have to be able to sort by Z-A as well. Is it possible for you to program this?

**Comment by mmartinortiz** [comment]
Hi,

From my user experience, I miss an option (maybe on the "settings" menu) for sorting by title. Maybe it is because how I use my notes, but for me the titles are more useful that the date of modification.

I saw in another issue that not getting overcrowded the settings menu is one of the reasons for not implementing this option on the sorting, but I do not see the settings panel so crowded.

Do you think that the sorting option could be integrated?

**Comment by korelstar** [comment]
See the answer above (https://github.com/nextcloud/notes/issues/298#issuecomment-466655703):

Notes in a specific category are sorted by title (stable view to find a known note at the same position again). Is this really not sufficient?

**Comment by mmartinortiz** [comment]
I do not categorize my notes. The main reason is because the categories only make sense for me on the web-side, when I'm working with the notes on my computer, they are plain Markdown files. 

The way I use to work with the notes is as follows (it could be that I'm not using the extension as it is intended): I write them from my desktop, using mainly Atom. When I need to check them from a different computer, I use the web interface, since I do not have the desktop client installed in those other computers.

**Comment by stefan-niedermann** [comment]
> The main reason is because the categories only make sense for me on the web-side, when I'm working with the notes on my computer, they are plain Markdown files

For your info: the categories are only plain folders and are synced, so editing them with your atom editor is still easy and possible :)

**Comment by korelstar** [comment]
@mmartinortiz
You can select "Categories" in the app navigation and then chose "Uncategorized" in order to sort your notes by name.
