### ISSUE TITLE
Better display of code blocks

### ISSUE THREAD

**Issue by jv-barsuk** [nextcloud/notes#305]
Code blocks are not displayed correctly. The grey background just ends after the last character and there is some space between the lines. Giving the `.CodeMirror .CodeMirror-code .cm-comment`Element the attribute `display: block;`would enhance the way it shows.
Then newlines in between just would need to get the right css-class and the way it looks would be great.

Now: https://imgur.com/N0clBhZ
After: https://imgur.com/RNvaahl

**Comment by korelstar** [comment]
You're right, but unfortunately, your fix breaks inline code formatting (i.e. `text ``code`` text` will be displayed as block, too). If you have a fix for this, I would be happy to include this in the next release!

**Comment by tnyeanderson** [comment]
```
span.cm-comment:only-child {
    display: block !important;
}
```

Now just figure out the whitespace :)

**Comment by korelstar** [comment]
Nice! Thank you very much, that's so cool! I will integrate this in the next release :tada:

**Comment by tnyeanderson** [comment]
*Do not include that code yet!* It renders weird on my system unless I also have the following:

```
.CodeMirror-line > span {
    padding-right: 0 !important;
}
```

Any one else see this issue? If I don't have that, the line-height of the `.CodeMirror-line` goes out of whack and I get a lot of vertical whitespace. Unfortunately there's no way to select that span more specifically, and the `!important` is necessary because CodeMirror injects inline CSS. Not sure how this may affect other things, **though I don't see problems yet**.

Only bug I see is that if you select text within a line of the code block, that line becomes white again. I haven't figured out a way to solve this issue yet.

New lines within a code block will also still be white, as described by the OP. Haven't figured that out yet either... CodeMirror spits out some really unhelpful elements and styles into the page.

**Comment by tnyeanderson** [comment]
There is a problem with the `padding-right: 0 !important` line. Lines that contain only a dash and space (implying a list item) will be invisible until text is added after it. It will have essentially 0 height, and makes editing lists confusing.

Anyone got a better workaround for the vertical spacing issue?

**Comment by korelstar** [comment]
Due to #290, we have huge changes in the editor. It looks to me, that the following code has no side-effects, any more:
```
.CodeMirror .CodeMirror-code .cm-comment:only-child {
    display: block;
}
```

Could you please test this again with the current code base, @tnyeanderson ?
