### ISSUE TITLE
Add Statuscode if Note is deleted

### ISSUE THREAD

**Issue by daehruoydeef** [nextcloud/notes#353]
I am developing a Third Party Nextcloud Notes Android App and I am using this API. 
I got frustrated to find out that many Nextcloud instances are really slow to respond, so developing a Third Party Client would need to cope with such behaviour ( I usually get respond times up to 1 minute), I would like to know for certain if a Note has been deleted by evaluating the status code.

**Describe the solution you'd like**
Add a simple Statuscode, for e.g 200 sucess if a note is deleted

Here is a Link to my App:
[NextNotes Android App](https://github.com/daehruoydeef/NextNotes)

**Comment by korelstar** [comment]
Those long response times are not typical. Is the server system or the network very slow?

However, I'm not sure if I understand your request correctly, since the app has already the following behavior:

- when deleting the note was successful, the status code `200` is sent
- when the note doesn't exists, the status code `404` is sent
- when an error occurs while deleting, the status code `500` is sent

I think this is a good behavior. You should check for status codes `200` or `404`. If you get one of those status codes, you can be sure, that the note was deleted successfully. Checking for `404` is important, because if there is a network error in the first delete request. Then, the server could have already deleted the note, but your client didn't received the response (timeout). When the client re-tries to delete that note, it is not there anymore and the server responses with `404`.

By the way: There is already an Android app for notes: https://github.com/stefan-niedermann/nextcloud-notes ; What's your intention to create another app? Maybe you could help with improving the existent one?

**Comment by daehruoydeef** [comment]
Sorry I probably mixed things up and did not double check. The behaviour is as it should be.

I am hosting my Nextcloud Instance via Hetzner, I talked to the support but the Network seems to be ok, cache is also enabled. I am still trying to find out why it is so slow for me.

Regarding the Android App, I am aware of the Original App and also used it but never got familiar with it. I wanted a more modern UI / UX and I also wanted to get into cross platform development. I am using Flutter and would like to also support iOS and maybe also Desktops in the Future to make the Nextcloud Eco System available to more users.
I think in the long run this will help grow the Platform by giving more choices to the user. 

Thank you for your hard work.
