### ISSUE TITLE
Docu for Categories / category handling

### ISSUE THREAD

**Issue by MarcusE1W** [nextcloud/notes#413]
The request is to document how categories work with notes, maybe in the Wiki.

Currently I was struggling a bit how to **create** categories (using an iPad and Firefox browser).
Searching the Notes app GUI I could not figure out how to create a category in the notes app.

Eventually I tried to just create a new folder in the files app. Still no luck. However after I have moved one note to the new folder the new category also shows up in the notes app. I am not quite sure if this is how categories are supposed to be created ?

Even after a new category is now shown in notes I can’t **move** the files between categories in the notes app, although there seems to be a option in the drop down menu in the sidebar, however only the current category is shown. Should moving categories also be done in the files app?

Once the suggested way to use categories is clarified I am happy to write a Wiki entry.

**Comment by raelb** [comment]
I too was perplexed as to how to create categories, expecting there to be a create button of some sort.

When there are no notes there is some information provided about how to use the app. Perhaps in that screen, some comment of how to create categories would be helpful.

**Comment by korelstar** [comment]
Thanks for the feedback! I think there are two aspects in your feedback:

## 1. Does changing categories work as expected?

The current workflow for setting a category is as follows:

- open the note in the notes app
- open "details" using the three-dot menu in the upper right corner
- you see the details sidebar on the right:
![Screenshot](https://user-images.githubusercontent.com/6277619/70847923-8ed65800-1e6a-11ea-8371-a268292267c8.png)
- when clicking on the current category, you can chose another category for the current note:
![Screenshot](https://user-images.githubusercontent.com/6277619/70847926-a01f6480-1e6a-11ea-8ba4-8c4818796f61.png)
- you can even type a new category name in that field in order to create and set a new category:
![Screenshot](https://user-images.githubusercontent.com/6277619/70847931-b6c5bb80-1e6a-11ea-85c2-e0a9c6cd88c8.png)

If this workflow doesn't work in your installation, please create a new issue for that.

## 2. How does a user get in touch with that workflow?

I agree that we should improve this. Based on your feeback, I propose these changes:

- Add "details" action to the note's three-action menu in the app-navigation (left side). With this, the "details" sidebar can be found easier.
- Add short explanation on the first-use-screen (shown when there are no notes in your profile).

I don't know if this is sufficient. If you have some other ideas, please write them down in this issue.

However, I don't think we should start writing a separate documentation in the wiki. I worry that such a documentation wouldn't be read since it's hard to find. On the other hand, it would be nice to have some kind of documentation in the app itself (e.g. together with some Markdown info, see #287). But there is no common way to integrate this in a Nextcloud app.

**Comment by korelstar** [comment]
Please see #416 for a fix.

**Comment by raelb** [comment]
> Add "details" action to the note's three-action menu in the app-navigation (left side). With this, the "details" sidebar can be found easier.

Is it possible to post a screenshot of what you have in mind, so I can get a better idea?

Not sure I noticed the 3 dots before. 
How about having a separate menu item showing the current category - which you can click on to change. Seems a bit buried in the Details screen.

**Comment by korelstar** [comment]
> Is it possible to post a screenshot of what you have in mind, so I can get a better idea?
![Screenshot](https://user-images.githubusercontent.com/6277619/70853721-02e81e80-1eb2-11ea-98b3-56ae592ba3e5.png)

> How about having a separate menu item showing the current category - which you can click on to change. Seems a bit buried in the Details screen.

There is already such an entry (category "Dev" in above screenshot). However, it's for showing all notes in that category (sets a filter to the list of notes). This is also a nice feature, which should be retained.

**Comment by korelstar** [comment]
Another option would be to add an `ActionInput` to this menu for directly changing the cateogry:

![Screenshot](https://user-images.githubusercontent.com/6277619/70865753-52395800-1f61-11ea-9891-fa65f686102a.png)

What about this approach?

/cc @nextcloud/designers @nextcloud/notes

**Comment by raelb** [comment]
I like that idea, but the disadvantage you mention (no drop down of existing categories) is quite serious. Would things be different if you were to implement this in the 3 dots to the right of the note?

**Comment by korelstar** [comment]
> Would things be different if you were to implement this in the 3 dots to the right of the note?

No, that's the same component. I'll try to add the possibility for a drop-down in the actions menu (see https://github.com/nextcloud/nextcloud-vue/issues/774).

**Comment by jancborchardt** [comment]
@korelstar can you look at iOS Notes for how they do categories/folders? It's quite simple and shows the hierarchy clearly.

This is also very related to what @ma12-co has been proposing with a move to a 3-column layout:
- AppNavigation: list of categories
- AppContentList: list of notes
- AppContentDetail: current note

And the AppNavigation would be collapsed by default even on desktop.

**Comment by korelstar** [comment]
No, I don't have any iOS devices. Could you provide screenshots?

**Comment by jancborchardt** [comment]
@korelstar I also only sometimes check the iOS device of my partner, but there’s plenty of resources online. :) A great starting point for Notes is this article, which includes the folder management and much more: https://www.macstories.net/stories/ios-11-the-macstories-review/8/

**Comment by korelstar** [comment]
I'm fine with this approach, but this requires some changes in `@nextcloud/vue`. Therefore, I opened a new issue over there: https://github.com/nextcloud/nextcloud-vue/issues/791

**Comment by BloodyIron** [comment]
I would like to add that as a non-Apple user the issue of self-evident usage of Categories with the web interface for Notes, really would benefit from love. Seems OS/browser agnostic. Looking forward to improvements rolling out!

**Comment by BloodyIron** [comment]
Some additional thoughts: (web interface)

1. Having the ability to move a note to a Category being on the right really does not lend itself to being obvious. Clicking on the 3-dots to move a Note is not only very obscure from a UX perspective, but also just one more click. I think this should be something handled on the left side.
2. I think there should be two ways to do this. a) clicking on the 3 dots on the note on the LEFT side (where your note is in the list), and instead of just seeing what Category it is already in (which, by the way, that existing is confusing), you instead can set the Category and/or create a new one (in the same step). b) when you click to "expand" the Categories on the left, there's a field for creating a new Category for the currently selected Note, perhaps "Type new Category for current Note" as the placeholder text.
3. With the above, or similar, methods to move Notes out of an Empty Category, I would expect the Category to have "0" beside it. But I would be okay with the Category being deleted (and the associated folder deleted too, to keep it organised). But I'm not sure if all race conditions have been fully explored here...

**Comment by korelstar** [comment]
Just an update of the current state: I'm still waiting for the implementation of https://github.com/nextcloud/nextcloud-vue/pull/616 in order to realize a three-column UI.

**Comment by ma12-co** [comment]
It's coming soon @korelstar :)

**Comment by ikesau** [comment]
Looking forward to this!

To clarify, under the current folder-based categorization system, a note can only belong to one category at a time?

I've seen markdown-based note apps use YAML front-matter to manage tagging/metadata, but presumably we've passed that fork in the road already.

Either way, thanks! I'll be keeping an eye out for ways I can contribute in the future. 👍

**Comment by korelstar** [comment]
> To clarify, under the current folder-based categorization system, a note can only belong to one category at a time?

Yes.

> I've seen markdown-based note apps use YAML front-matter to manage tagging/metadata, but presumably we've passed that fork in the road already.

There are still the open issues #299 and #164 which are related to this. But currently, there is no concrete plan to implement them.

> Either way, thanks! I'll be keeping an eye out for ways I can contribute in the future. 👍

Any contribution is very welcome! There is much to be done and too less free time for this 😉

**Comment by cornzy** [comment]
I also did not find the three dots on top right to open the details view. Hence I always switched to files app to change the category, quite disturbing. So I searched and found this issue.

I think the title should be corrected, the discussion is no longer about documentation.

I tried to switch the category by any butten on the dot menu on the left and also tried drag&drop. So I think having any option in the dot menu on the left is most expected behavior.

**Comment by newhinton** [comment]
Wouldn't it make sense to rename and restructure the categories to folders anyway? With #842 this would improve usability, and it would also fit better to how markdown files are usually handled. 

The editors i have encountered are ususally assumming that notes are structured by folders, and categories are a rather foreign concept. In my opinion, it also does not work really well:
E.g. i have the following notes in my notes folder:
```
folder1/note1.md
folder2/folder3/note2.md
folder2/folder3/folder4/note3.md
```


This currently results in two categories in the sidebar:
`folder1` and `folder2`
and in addition to those, subcategories:
`folder3` and `folder3/folder4`

This leads to a confusing state:
What differentiates `folder1` and `folder3`? Why are they not the same?
Why are `folder3` and `folder3/folder4` the same? They share the same difference as `folder1` and `folder3` (different folder depth) but are not on the first level. This is hard to understand on a quick glance, and does not lead to a clear navigation.

Therefore i propose to restructure (and maybe eventually rename) the caterories the following way:
1. Finalize #842. This is the most important step because it allows us to actually realize step 2.
2. Always handle the outermost column as the center of the application (favorites, "home", last used notes, etc) and the inner column as the note/category-view. 

The note/category-view should now behave like browsing the filestructure of a filesystem: Show categories in the current scope, and notes below them. If a category is clicked, replace the current scope to the new one, and repeat.

This has the benefit that there is no difference between the categories, even if they are on different levels, and with breadcrumbs it will be even more easy to distinguish them. That also should allow us to be easily enable to create a note in a specific location (since we always have the proper scope) or move it there.

**Comment by Bondarz** [comment]
Hello, do I see it correctly that I can not create a category within the browser on Firefox? At least I have not found an "add button". Via Android app I can create categories. Those then show up within Firefox as well.

Thanks

**Comment by Bondarz** [comment]
Ahhhhhh, thank you @stefan-niedermann. It's unter "Details" if i create a new note. Nice hide ;)

Greetings

**Comment by joshtrichards** [comment]
The design matters discussed here pertaining to categories have been implemented for a bit now. And the old sidebar is gone.
