### ISSUE TITLE
List of notes on nextcloud inside browser is broken (design issue)

### ISSUE THREAD

**Issue by llukee** [nextcloud/notes#426]
![Screenshot_2019-12-31 Neue Notiz (7) - Notizen - lukasoppler ch](https://user-images.githubusercontent.com/31471027/71628638-296bc080-2bf9-11ea-8430-be4fbbc2d41f.png)

I just updated the nextcloud app the latest version and it seems that the list design is somehow broken. I am using Nextcloud 16.0.4

Best wishes

**Comment by korelstar** [comment]
Thanks for this bug report! Please give more information about your environment, since I can't reproduce this issue. All information from the issue template could be helpful:

**Server (please complete the following information):**
- Notes app version: 
- Nextcloud version: 
- OS: 
- Web server: 
- PHP version: 
- Database: (irrelevant here)

**Client (please complete the following information):**
 - Browser (incl. version): 
 - OS: 

----

Did you tried to clear the browser cache and server cache (try to restart your web server and PHP-FPM (if applicable))?

**Comment by lensaffair** [comment]
I can +1 that. Same weird design since latest Notes update. Here's my setup:

**Server (please complete the following information):**
- Notes app version: 3.1.0
- Nextcloud version: 16.0.1
- OS: (unknown: shared webhosting)
- Web server: Apache (hard to tell: shared webhosting)
- PHP version: 7.2.26


**Client (please complete the following information):**
- Browser (incl. version): Vivaldi 2.9.1719.3
- OS: Windows 10/Linux Mint 19 Cinnamon

**Comment by korelstar** [comment]
Thanks for sharing your details! I just installed the Vivaldi browser (2.10.1745.23) and tested, but here is everything fine. @llukee Which browser do you use?

@llukee @lensaffair 
Could you please try to deactivate, then remove the notes app and re-install it afterwards? All notes are kept during removal.

**Comment by lensaffair** [comment]
Hi @korelstar,
did that - unfortunately the issue remains the same. I checked Firefox 71.0 (Win10) and Chrome 79.0.3945.88 (Win10) with cleared cache as well: same, same. :(

**Comment by korelstar** [comment]
Okay, I just installed Nextcloud 16.0.1 and I can reproduce the issue. However, after upgrading to the latest bugfix release Nextcloud 16.0.7, everything is fine.

Hence, please update your Nextcloud installation!

**Comment by llukee** [comment]
Perfect, that solves the problem, tThank you very much!
