### ISSUE TITLE
Notes list display problem

### ISSUE THREAD

**Issue by SamyMe** [nextcloud/notes#434]
After updating to new version I have this wierd display problem (firefox and chromium ubuntu 18.04)
The star is on top of the note title, not left.

![Screenshot from 2020-01-14 09-18-23](https://user-images.githubusercontent.com/7459397/72326212-118f4480-36af-11ea-9287-df32cf20daef.png)

**Comment by stefan-niedermann** [comment]
Please have a look here: https://github.com/nextcloud/notes/issues/426#issuecomment-570176286

This issue looks like a duplicate. Which Nextcloud version exactly do you have installed? According to @korelstar the issue was reproducable with Nextcloud 16.0.1 and disappeared after upgrading to the latest bugfix release 16.0.7.

**Comment by SamyMe** [comment]
Oh ok I didn't see that one. I have version 15.0.2. I'll try upldate.

**Comment by SamyMe** [comment]
Updating nextcloud did fix the issue.
