### ISSUE TITLE
Allow translation of default folder

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/notes#486]
Currently when user is entering the app for the first time the "Notes" folder is created no matter what language of Nextcloud is set. It would be great if this name/location could be translated or set by administrator.

**Comment by korelstar** [comment]
Sound reasonable. I suggest the following 

1. if notes folder was manually set (user setting), then use this folder
2. otherwise, if a folder called "Notes" already exists, use this folder
3. otherwise, use translated folder name and save this as user setting.

The second priority is required in order to be compatible to existing users. Saving as user setting is required, since the translation can change over time, but the notes still have to be accessible without manual interaction.

Personally, I don't see a need for an administrator setting and we do not have any administrator settings, currently.

What do you think about this approach, @nextcloud/notes ?
