### ISSUE TITLE
Support ascidoctor (and possibly other formats)

### ISSUE THREAD

**Issue by Leon0402** [nextcloud/notes#492]
It would be great to have support for different technologies, not just Markdown. Concretly I would like to see asciidoctor support, it's quite similar to Markdown, but doesn't have dialects (but is standardized) and provides a few more things, is a little bit more consistent etc. 

In generel, it might be possible to have an api to support any kind of backend? So for example that latex could be supported as well. From my point of view, Notes could create an api, so a processor can get the input file Note.tex and produce a pdf for example and give back a pdf, which Notes can then display.

**Comment by korelstar** [comment]
Hmm. It's already hard enough to have a good editor for markdown. If we would add another markup language, we would have to use a second editor for that. In my view, this is too much for an app which focuses on easy notes taking. Therefore, I assess this feature request as out of scope.

However, we aim to replace the current editor by the Nextcloud Text app's editor (see #331). Hence, it will depend on the Text app to support asciidoc (you could open an issue for this over there).

Due to these deliberations, I will close this feature request for now.

**Comment by Leon0402** [comment]
Just out of interest, how much backend is actually involved in it?
I actually don't know how it works for markdown/asciidoctor and similar markup languages, but for example latex is being compiled. So in case of latex the backend would be kind of small, just running a terminal command basically. 

How is it with Markdown. Do you have written your own markdown interpreter? (and therefore would need to to the same for ascidoctor)?

Regarding the text editor, in general I think this is a good idea, but there is one question I have. The Text app is as far as I can see an what you see is what you get editor. So in contrast to notes, the markdown code you write is converted directly. While this is kinda cool in some way, it's also really annoying :D ( I haven't fully made a decision, but I think it's more annoying than cool). 
I really like the toogle functionality in Notes (perhaps the best would be to use the behaviour of text as "view + edit" mode and have the notes "edit mode"). So what's the plan for this? Will notes loose the ability to write code in own mode, and display it in another?

**Comment by korelstar** [comment]
Currently, the backend only processes markdown for auto-title generation. The editor and viewer in the web-frontend are based on external libraries. But a new editor requires always some adoptions. Also, there are third-party clients that use our API -- these would require to integrate a new editor, too. Since these clients are implemented for other platforms, this is not an easy thing.

Regarding the text editor: my plan is to eliminate the current distinction between edit and view mode. But please have a look at the [Nextcloud Text repository](https://github.com/nextcloud/text). There is already an issue regarding [plain text editing](https://github.com/nextcloud/text/issues/439). When that will be implemented, the Notes app will also have this feature.

**Comment by Leon0402** [comment]
@korelstar Ah I see, that makes sense.

Well the issue doesn't look like it's coming any time soon. Under these circumstances, the integration of text seems more like a step backwards than forwards.

**Comment by bohni** [comment]
> hard enough to have a good editor for markdown

markdown (also asciidoc) was invented to write as plain text and then render it. There should not be the need for a "good" editor 😉
