### ISSUE TITLE
Local backup feature

### ISSUE THREAD

**Issue by ivnvitx** [nextcloud/notes#494]
Just in case Nextcloud goes crazy, it would be cool to have configurable local backups on the phone.

**Comment by stefan-niedermann** [comment]
Uhm. what? What exactly do you mean with "goes crazy" :smile: ? I think there are way better solutions for taking backups than directly building it into the Notes app. For example you could use the [default Desktop or Android clients](https://nextcloud.com/install/#install-clients) to synchronize your `Notes` folder - then you have a backup :) Why not use them as the most simple imaginable solution?

There are plenty of ways from using any `WebDAV`-client to cronjobs using FTP if you want to have more control about how where and when to do backups.

**Comment by korelstar** [comment]
I strongly recommend to use server-side backups instead of a client-side backup. Please see this discussion for more information: https://github.com/nextcloud/notes/issues/437#issuecomment-599127170

Please note also that this is the repository for the server app. The repository for the Android app can be found here: https://github.com/stefan-niedermann/nextcloud-notes/
