### ISSUE TITLE
Newly created notes still change their title according first line

### ISSUE THREAD

**Issue by godfuture** [nextcloud/notes#507]
Hi, just tested the manual filename functionality introduced with https://github.com/nextcloud/notes/issues/190.

I noticed that fresh notes still adjust their title to content from first line. This also applies, if you renamed the note before editing. If I switch to another note and back, this behavior does not occur anymore and the title stays unchanged. This means, if the user creates a new note, specifies the title and starts typing, the just specified title will be lost. But if the note was switched at least one time, the title stays even the content is being adjusted.

What is expected?
...that automatic title adjustment is disabled from first second. The tile can only be adjusted by renaming the note manually.

V3.3.0

**Comment by korelstar** [comment]
We should differ between two scenarios:

1. After creation, the user sets the title manually. After that, the title must not change automatically based on the content. => I will fix this bug.
2. After creation, the user writes text into the note without setting a title manually. Instead of having a note called "New note", the title should have a helpful title. Therefore, an automatic change is correct. See also https://github.com/nextcloud/notes/issues/190#issuecomment-394526741

Thanks for reporting this issue. The first scenario is indeed not as intended.
