### ISSUE TITLE
Inconsistency between API version and path

### ISSUE THREAD

**Issue by phedlund** [nextcloud/notes#533]
**Describe the bug**
The OCS capabilities API returns the supported API versions of  Notes, currently `["0.2", "1.1"]`. However, when calling the Notes API the expected path is either `/v0.2` or `/v1`

**Expected behavior**
The API paths should match the API versions.

**Server (please complete the following information):**
- Notes app version: 3.5.0
- Nextcloud version: 18.0.5
- OS: Ubuntu
- Web server: Apache
- PHP version: 7.x
- Database: Postgresql

**Client (please complete the following information):**
 - CloudNotes for iOS 

**Log files**
▿ 2 elements
  - 0 : "0.2"
  - 1 : "1.1"

**Comment by korelstar** [comment]
That is intended. The path to be used depends on the API's major version. According to semantic versioning, the major version for 1.1 is 1, and for 0.2 it is 0.2 (since it's below 1). Hence, v0.2 is a special case (which exists for historical reasons, only).

#### Why is the path based on the major version and does not include the minor version?
I've tried to document the motivation behind this approach in the [API documentation](https://github.com/nextcloud/notes/blob/master/docs/api/README.md#versions-and-capabilites).

But let's have a look at a concrete example: The change between API v0.2 and v1.0 was a breaking change (no automatic title generation), so we had to provide a new API endpoint (`/api/v1/` instead of `/api/v0.2/`). In contrast, the change between v1.0 and v1.1 was a non-breaking change (new search parameter). That's because clients that implement v1.0 can still use the same API endpoint, even if it implements v1.1. Therefore, both use the same path (`/api/v1/`).

In an alternative approach, we had to create a new API endpoint (path) for the non-breaking change in v1.1 (e.g. `/api/v1.1/` or `/api/v2/`). This would have resulted in increased maintenance efforts on both client side (switch the API version more often) and server side (support more API versions in parallel).

That's the motivation for the chosen approach. In the practical doing of implementing a client for a specific API version, you simply must use the path that is documented in the [API documentation](https://github.com/nextcloud/notes/blob/master/docs/api/v1.md#endpoints-and-operations). When requesting OCS capabilities from the server, you must walk through the list of supported API versions and for each version do:
1. parse the version string (e.g. `1.2`) and gather the major version (here: `1`) as well as the minor version (here: `2`)
2. check if you support the major version and then check if the minor version is greater or equal than your minimum required minor version for that major version

Then use the highest API version to which this requirement applies.

Please don't hesitate to ask more questions on the chosen approach and also give feedback if you don't agree with it or if you think we should improve the documentation.
