### ISSUE TITLE
Make keyboard shortcut for preview toggle customizable

### ISSUE THREAD

**Issue by tobenschmidt** [nextcloud/notes#574]
**Is your feature request related to a problem? Please describe.**
It's great to have a keyboard shortcut for preview toggle. But with a german keyboard layout the shortcut _CTRL + /_ requires two hands and three keys to toogle priview.

**Describe the solution you'd like**
It would be an improvement to be able to customize the shortcut having to use less hands and/or keys.

**Comment by korelstar** [comment]
Thanks for your feedback, @tobenschmidt. There was a long discussion (see https://github.com/nextcloud/notes/issues/505) on which shortcut should be used for this. `CTRL + /` was chosen since there are no conflicts with other apps.

I'm open to change this shortcut to another one (if there is an agreement with the @nextcloud/designers team). But we will not implement a custom setting for this, since the main goal of this app is to provide a simple, uncluttered interface for distraction-free notes.
