### ISSUE TITLE
The app can't input Chinese, Japanese etc.

### ISSUE THREAD

**Issue by izuolan** [nextcloud/notes#59]
![](http://i.imgur.com/6OEmyoo.gif)

Because the auto save break the input method.

Normal Input :
![](http://i.imgur.com/rwIDsFj.gif)

**Comment by korelstar** [comment]
Do you think this issue can be solved, if *auto-save* is only called after a certain timeout (e.g. 2 seconds) after the last input typed?

**Comment by izuolan** [comment]
Don‘t interrupt author input when note auto-save. So timeout(Interval) cannot fix this problem.

**Comment by HuidaeCho** [comment]
I cannot type Korean either. Is it possible to add a setting where you can disable auto-saving and don't interrupt user typing? I didn't have this problem before when there was no support for Markdown. Probably, it's an issue in the Markdown library?

**Comment by Acris** [comment]
Maybe this bug is come form Ace, see https://github.com/nextcloud/files_texteditor/issues/44

**Comment by jancborchardt** [comment]
We should actually support this, but have to find a proper way to handle this.

@izuolan @HuidaeCho is it possible for the Notes app to know that an input help like this is used? Because then we could halt the saving as long as the popover is open.

Also, is it not possible to save without messing with the popover? cc @nextcloud/notes 

@izuolan also, what is that editor you showed where the input works and it autosaves? And how does it do that?

**Comment by izuolan** [comment]
LOL, This issuse was fixed a few months ago, I don't know what happened. You can close this issue.

**Comment by jancborchardt** [comment]
Great, then that's probably because we moved from another editor to SimpleMDE. :) Thanks for letting us know it works now.
