### ISSUE TITLE
Multiple checkboxes in one line

### ISSUE THREAD

**Issue by natrius** [nextcloud/notes#643]
It would be nice to have the posibility to get multiple checkboxes in one line. Its maybe not everytimes useful, but for example when getting recommendations for books one checkbox is for "owning" and one for "read". Just as an example. 

**Describe the solution you'd like**

Treat every `[ ]` as a checkbox, not just `- [ ]`

Its probably niche and if its a lot of effort, just scrap it. Guess will find something else as well :)

**Comment by korelstar** [comment]
The notes app uses Markdown syntax for formatting text. As far as I know, Markdown doesn't support multiple checkboxes in one line. Therefore, I don't think this should be implemented.

As workaround, you could use Unicode characters in order to document this. There are some meaningful characters for this purpose, e.g.: ☐ (U+2610), ☑ (U+2611), ✓ (U+2713)

**Comment by dilomo** [comment]
I do think this is essential feature and its not even difficult to implement. Do not understand why its not already implemented..

**Comment by stefan-niedermann** [comment]
@dilomo because the Notes app aims to fulfill the commonmark markdown specification.According to the specification this is no valid markdown.
Even in other markdown specs like GitHub flavored markdown this is very very uncommon.

- [x] test - [ ] another

**Comment by dilomo** [comment]
@stefan-niedermann I'm referring to something like that: 

[  ][  ][  ] Drawing A
[  ][  ][  ] Drawing B ... 

In that case you can check different things that should be present on each item or these check boxes can be for a different phase of a project. I would like to propose a change to Markdown standard then as currently it is targeting mostly programmers but obviously other people would have more use cases of it. Would you know where would be the best place to post a request?

**Comment by stefan-niedermann** [comment]
The same reason - It is no valid markdown according to the commonmark spec (as well as GitHub flavored markdown and others as you see).
Use nested lists, like

```
- [ ] Main 1
  - [ ] Sub 1
  - [ ] Sub 2
- [ ] Main 2
  - [ ] Sub 1
  - [ ] Sub 2
```

- [ ] Main 1
  - [ ] Sub 1
  - [ ] Sub 2
- [ ] Main 2
  - [ ] Sub 1
  - [ ] Sub 2

> different phase of a project

This is a *distraction free Note taking tool*. It was never (and will never) be meant as a project organization tool. I recommend you to check out the [Deck](https://apps.nextcloud.com/apps/deck) app, or other alternatives like [Tasks](https://apps.nextcloud.com/apps/tasks) which probably cover your needs better.

> essential feature [...] obviously other people would have more use cases of it.

With far more than 10.000 active users, you are the very first who requested this feature. (Excluding the original poster because your feature request is a different one). Are you really sure that it is not you who has a quite special workflow for *taking notes*? :wink:
Honestly,  `[ ][ ][ ] Drawing A`, this looks *so weird*, that i am pretty sure, that *no* non-techie will ever get what kind of crosswords this should portrait :smile: 

>  I would like to propose a change to Markdown standard then

You can find the specification as well as discussion forums for commonmark here: https://spec.commonmark.org/

**Comment by dilomo** [comment]
@stefan-niedermann Haha I know I have a bit different requirements about organisation. Tasks is nice but looks too complicated. I just have a check procedure for the same item but 3 times at different time. I think notes is the level of simplicity I need with some more levels of organisation and a bit more feature rich writing pane. Right now  the dash does not disappear in preview mode. Anyway thanks for the fast response and insights. 

Thanks for the link. I'll check it out :)
