### ISSUE TITLE
Text formatting syntax must not be visible in notes

### ISSUE THREAD

**Issue by MiMoHo** [nextcloud/notes#651]
**Is your feature request related to a problem? Please describe.**
I prefer text formatting tools where the Markdown syntax does not appear visually in the text.

**Describe the solution you'd like**
Parameters for links, bolt or italic text should be handled in the background so when copying text, the formatting e.g. "_" or "**" is not copied as well. Thereby, underlines in text for example in weblinks are not accidentally interpreted as italic setting.

**Comment by stefan-niedermann** [comment]
Here my personal 2¢: I disagree. Notes is not meant to be a "formatting tool". Notes is **not** a text processor like word, or anything similar. For this purposes various solutions like Collabora or OnlyOffice exist.

Notes is a distraction free plain text writing tool with the *bonus* to provide a few highlights for common markdown syntax. The reason we chose plain text / markdown files as storage backend is the universal flexibility, because the user has the complete control over the contents.

On the other hand, i think it is good the current way Notes is already highlighting the actual content over the punctuation (the punctuation is in a lighter grey, while the actual content shines in a good contrast).

The **only** way to fulfill your feature request in *my personal opinion", is to still support entering markdown and silently add formatting and remove the punctuation - but only in the visual representation (means: if you open the note in e. g. the Windoes Notepad, the punctuation must still be present).
But in this scenario: How to remove punctuation? The only answer for me is a dependency to https://github.com/nextcloud/notes/issues/200 for [this reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-arent-there-any-buttons-to-apply-formatting).

**After all Notes will in the end fail to hide complexity and result only in more confusing because it is no longer transparent how something works.**

cc @korelstar @nextcloud/designers 

---

Merry X-Mas and stay well! 🎄

**Comment by korelstar** [comment]
Closing in favor of #331.
