### ISSUE TITLE
Undo/redo functionality

### ISSUE THREAD

**Issue by MiMoHo** [nextcloud/notes#659]
**Is your feature request related to a problem? Please describe.**
Undo feature needed to revert changes before and after they get saved and synced.

**Describe the solution you'd like**
A changelog history in the notes overview to go back in time as well as an undo and redo button to be reached via the 3 dots in the top right note's options. 

**Describe alternatives you've considered**
Manual backup of notes – very inconvenient.

**Comment by korelstar** [comment]
This has two aspects:
1. provide buttons for undo and redo while editing => this will be fixed by implementing #331
2. show a version history => this is already discussed in #144

Since (2.) is a duplicate, let's concentrate on (1.) in this issue. We can keep this open until we've finally implemented #331.

**Comment by waltercool** [comment]
Up on this.

It's completely not understandable why it doesn't contain any undo funcionality.

I lost so many notes by just a wrong paste or modification, and no way to recover the data.

**Comment by nottheend** [comment]
I also suffered already many times from overwriting notes 🥲

**Comment by juliushaertl** [comment]
This has become available with the rich text editor with Nextcloud 26.
