### ISSUE TITLE
Replace mdEdit

### ISSUE THREAD

**Issue by phsc** [nextcloud/notes#7]
mdEdit seems to be unmaintained (the last commit was on the 17th October 2015). Therefore, it would maybe make sense to think about a replacement.

A really nice editor, for example, is [SimpleMDE](https://simplemde.com/) (see also [Github repo](https://github.com/NextStepWebs/simplemde-markdown-editor)).

**Comment by Henni** [comment]
I'd consider this low-priority for now. mdEdit currently works fine and it might be difficult to find a well maintained replacement (SimpleMDE last commit Jun 14).

**Comment by Henni** [comment]
After getting into working with the notes app again in the last few days, I once more noticed a few issues which might be caused by mdEdit (maybe including #13). So I might take a look at SimpleMDE soon or any other Markdown editor I find.

**Comment by gsantner** [comment]
Markdown instead of the WYIWYG-HTML-Editor would be really great!
I'm using SimpleMDE on my [Gogs](https://github.com/gogits/gogs/tree/master/public/plugins/simplemde-1.10.1) instance, and I absolutely love it :D.

**Comment by gsantner** [comment]
I just found this project: <https://github.com/janis91/nextnotes>
It uses SimpleMDE. I'm just surprised why there are like 10 note apps out there.

**Comment by phsc** [comment]
Yes, it would be really worth thinking about focusing development efforts on one notes app. It does not really make sense to put a lot effort in migrating this notes app to SimpleMDE, if there is already one, that uses SimpleMDE. The same for the tags feature (see #8).
But this has to be agreed and decided by the app maintainers.

@Henni @LukasReschke @janis91
Any oppinions?

**Comment by gsantner** [comment]
I created an issue about the nextnotes future (before reading @phsc 's comment): 
<https://github.com/janis91/nextnotes/issues/39>

**Comment by janis91** [comment]
I am completely with you:

It would make much more sense to focus on one app.

Originally nextnotes was the idea of learning, how to build an app for nextcloud, for me.
After I created it and just build a little bit more and had much more ideas, I actually realized, that there are much more notes apps and also that I have got ideas which are not on the actual roadmaps of eg. this project. For Example: I want to share the notes I take (kind of like a blog) to external parties. As well as I want to have a feature for collaborating with external parties.

These features are not integrated yet, but I definitely want to do this (because I want to use these myself). Maybe we can come together about those ideas and so on. Then I would suggest to work together!

Another suggestion:
Maybe we can talk about this on 13th december? (nextcloud Meetup in Stuttgart: [https://www.meetup.com/de-DE/nextcloud-stuttgart/events/234951272/](https://www.meetup.com/de-DE/nextcloud-stuttgart/events/234951272/))

**Comment by Henni** [comment]
I have worked on a SimpleMDE integration few weeks ago. I'll push the branch in just a second.

Regarding the recent comments:
There have been mainly two notes apps:
This one and OwnNote
While this apps aims to offer a minimal interface and experience OwnNote goes towards a WYSIWYG editor (AFAIK).
@janis91 It would be really great if you could help out with this app, when you have time (maybe after your masters degree :wink: ). I'd love to extend this app with sharing/exporting features.

We should all aim to not create forks/clones of similar apps and instead work together on a single, well maintained, feature rich project. I have seen this happen too often with ownCloud alone (calendar, calendar-rework, calender-deluxe and probably some more I missed)

I won't make it to the Stuttgart Meetup, but I'll be at the Munich Meetup, if you want to discuss the next steps in person. Alternatively we still have enough other channels (Issues, IRC #nextcloud-dev or #nextcloud-notes if you guys are interested)

**Comment by putt1ck** [comment]
Happy to test/document/support any notes app that has sharing, maybe directly available within the notes list (as per files/folders in NC general) and/or via an export to file feature, where the export is to selectable location within the NC install.

Latter option use case scenario: team member been investigating how to solve an issue, keeps notes of thoughts, solutions tried etc.. Reaches solution PoC state, wants to start more formal project: exports note to an existing shared team folder as seeding action.

**Comment by ThomasDaheim** [comment]
Just to throw in one thought here: I would definitely go for a notes app that only stores info using file system. I'm using ownNote (have developed a java frontend for it as well...) since it allows me to work "offline" in the editor and have the nextcloud client do all the syncing for me. No need to use an API or anything, just plain text editing.

I could also support any development here by e.g. testing...

**Comment by janis91** [comment]
@Henni Unfortunately, I will not have the opportunity to get to the Munich meetup. But as you mentioned, there are other ways to get in touch.

I think it would be much easier to have a discussion about some roadmap. I think there are plenty of ideas which are possible to implement, but some have to get excluded, as they might be off-topic in sense of a real notes app. Others however are maybe worth to get more focused (examples: Search and Tags).

BTW I am completely with you: 

> We should all aim to not create forks/clones of similar apps and instead work together on a single, well maintained, feature rich project.

**Comment by putt1ck** [comment]
Q. would changing the editor code make select copy/middle click paste work? One of those bits of functionality you get very used to when you have it. 
I notice the Github comment window supports Markdown and select copy/middle click paste...

**Comment by jancborchardt** [comment]
@ThomasDaheim @putt1ck I added you to the organization and the Notes team, welcome to the party! :tada:  :)

**Comment by ThomasDaheim** [comment]
That was fast... Unfortunately, my php-Skills are not that great - just enough to do small tweaks

**Comment by jancborchardt** [comment]
@janis91 oh and I added you too of course. :) Looking forward to great collaboration on a nice Notes app.

@ThomasDaheim of course, any help is appreciated. :) Testing, documentation etc – I’m a designer myself. Also depending on where you live, you could join one of our meetups: https://www.meetup.com/topics/nextcloud/global/ – or start one! :)

**Comment by putt1ck** [comment]
My coding mojo considerably less  than @ThomasDaheim - but can definitely ~~break stuff~~ test & document (and might be able to find some development resource to contribute)

**Comment by ThomasDaheim** [comment]
@jancborchardt  Thanks, will have a look. And probably raise the average age of participants by a few decades :-)

**Comment by gsantner** [comment]
@janis91 @Henni 
Whats the current state of the project? has the current code any future?
Is somebody working on a rewrite?

I'm asking because I see a lot of new issues and PRs, and I don't know whats going on currently.

**Comment by ThomasDaheim** [comment]
After some time I'm back looking into notes options. Unfortunately, there is one thing that keeps me from switching ownnote to notes: I love WYSIWYG editors and I think they're a great invention :-) Using simplemde would be at least a step towards that

How hard would it be to switch to something even more WYSIWYG (e.g. https://bevacqua.github.io/woofmark/)? Since @Henni already managed to do for simplemde it might not be that hard...

**Comment by putt1ck** [comment]
+1 for woofmark (having checked it handles select copy/middle click paste properly 👍 )

**Comment by olantrust** [comment]
Woofmark allows wysiwyg, html, and markdown input modes, and preserves the data across those modes. Thanks for highlighting it @ThomasDaheim 

This would be ideal for achieving the goal of a single note editor. There isn't another obvious and maintained candidate that works across those modes.

Without working across those modes, it would likely be that the Note app function remains splintered - most lay users (all our users included) only want wysiwyg/html, and other users want markdown. 

We can have both now.
