### ISSUE TITLE
Notes with emoji in the title can't be opened and can't be deleted

### ISSUE THREAD

**Issue by Magneticdud** [nextcloud/notes#721]
I accidentally created a note with emoji in the title by pasting a whatsapp conversation. I used the android client.

The file is created:

![image](https://user-images.githubusercontent.com/2940598/119120517-a9800980-ba2c-11eb-8543-7b8c7aa3f8b2.png)

Both the web and the android client can't show or delete the notes

![image](https://user-images.githubusercontent.com/2940598/119120773-f7950d00-ba2c-11eb-9612-902376e53b50.png)

In the Files app the note is also shown with the ??????? in filename instead of the emoji

## Server
Please complete the following information.

- Notes app version: 4.0.4
- Nextcloud version: 21.0.2
- OS: Ubuntu 20.04
- Web server: Nginx
- PHP version: 7.4
- Database: Mysql 8

## Client

- Any

**Comment by stefan-niedermann** [comment]
Hmm, just tried to reproduce it with the Android app `v3.4.3` by tapping on the ➕ button, inserting an `🙂` emoji with the keyboard, and waiting for the auto-save.
After returning to the list view, the note was synchronized to the cloud (no 🔁 icon at the note).
I was able to delete it via swipe to delete and check whether it was still present at the web UI - it wasn't.

**Comment by korelstar** [comment]
Nextcloud, the Notes app  and the Android Notes App should work with Unicode characters in the filename. However, MySQL may require a special configuration in order to store 4 byte characters that are required for emoticons. Please check this manual for the correct configuration: https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html

Does this fix the issue?

**Comment by Magneticdud** [comment]
Indeed it might be that!

My database is utf8, not utf8mb4

Monday I'll try that, I'm sure the issue is caused by my database then, not by nextcloud
