### ISSUE TITLE
Ability to change default file extension

### ISSUE THREAD

**Issue by pprevos** [nextcloud/notes#722]
I am n Emacs Org-Mode user and would love to be able to select ".org" as an extension.

It would be great to have the ability to change or add default extensions (currently only .md or .txt) through a config file.

The alternative I am working with is to convert the .md notes to Org in Emacs. I can view Org files made in Emacs in NextCloud, but cannot create new .org files with NextCloud.

Org-Mode is growing in popularity and non-Emacs-systems, such as Hugo and GitHub are now supporting this format.

No biggie, just a nice to have.

**Comment by stefan-niedermann** [comment]
@korelstar please note, that this is explicitly **not** a request to support `org-mode` as editor or viewer ([i already talked to the author](https://help.nextcloud.com/t/writing-notes-in-org-mode/116993/2?u=stefan-niedermann)). It is just a request to make the available file extension options configurable via a config file (where `.txt` and `.md` should stay the default options of course).

**Comment by korelstar** [comment]
I see. Since we already accept files with this extension as notes, I think it's okay to allow this to be set as default extension.

Should we then allow to set each of the accepted extensions? See https://github.com/nextcloud/notes/blob/v4.0.4/lib/Service/NotesService.php#L174

**Comment by korelstar** [comment]
But should we really differentiate between config file and GUI? How could users find the config file option? Shouldn't we instead provide all allowed extensions in the drop-down?

On the other hand, when implementing this using the config file approach, this would fix https://github.com/nextcloud/notes/issues/629, too.

Any opinions? I have to think about it.

**Comment by stefan-niedermann** [comment]
Huh, i wasn't even aware that all of those extensions are already recognized :smile:... Good question.
I think it will be simpler for users to choose between `.txt` and `.md` plus explicitly custom extensions which have been configured explicitly by the user as requested in this issue.
I wouldn't offer all of those as available extensions by default though, even if the app is able to recognize them.

I understand from a maintenance point of view that you don't want to have multiple lists, but from a UX point of view, it's simply overwhelming for a user, especially because `markdown` and `note` are pretty uncommon file extensions...

Will also think about it... and i guess i need a REST endpoint to fetch the available extensions if the list isn't static anymore...

**Comment by korelstar** [comment]
I still have a problem with restricting the user choice to `.txt` and `.md` and -- at the same time -- allow the user to chose other extensions using a more complicated way. In fact, the "more complicated way" means, that a normal user can't use it, but you need to be an admin in order to edit the config file.

What I could imagine instead is to introduce an user-independent/app-wide setting as requested in #629. Per definition, this setting can only be changed by an admin. Therefore, we could allow all extensions here, since I can expect that an admin is able to deal with uncommon file extensions. User can overwrite the app-wide setting with the simple ones or stick to the default (which may be `.txt` or `.org` or ...).

@pprevos Would this be sufficient for you?

--------

### Implementation details (draft)

The setting can be set on the command line using `php occ config:app:set notes defaultFileExtension --value=".org"`. In the first step, I will not provide a user interface for this, since I will document this as "beta" feature.

The settings API has to be changed. New sections for app-wide settings (read-only) and static configuration (read-only) have to be added. An example return value could be:
```
{
  "static": {
    "version": "4.1.0",
    "apiVersions": ["0.2", "1.2"],
    "fileExtensions": [".txt", ".org", ".markdown", ".md", ".note"]
  },
  "app": {
    "defaultFileExtension": ".org"
  },
  "user": {
    "fileExtension": ".md",
    "notesPath": "My notes"
  }
}
```

What about that?

**Comment by pprevos** [comment]
Hi @korelstar, that is a reasonable solution for me. I am not an admin - I use a paid server, so an option in the dropdown list would be ideal. 

I am not looking to change the default from .md, just the option in the menu to create a .org file would be very useful.

Thanks for considering my request.

**Comment by korelstar** [comment]
Okay, then we have no choice and the only possible solution is to show all extensions in the settings drop-down. Still a veto @stefan-niedermann ?

**Comment by stefan-niedermann** [comment]
Personally i think that the common extensions `.md` and `.txt` are enough and other, uncommon extensions will confuse users (for example `markdown` and `note` will not be recognized as file extensions).

Using `.org` will bring no benefits in the Notes editor. Those files should be edited with an appropriate tool and synchronized with the Nextcloud Sync client in my opinion.

Do not consider this as a "veto", but as a 👎  from me.

**Comment by pprevos** [comment]
Org-Mode is not as uncommon as it might seem. 

GitHub accepts it and fully parses them. Example: https://github.com/pprevos/EmacsLife

Adding this option would render the Nextcloud note-taking app very useful for tens of thousands of Org-Mode users.

**Comment by stefan-niedermann** [comment]
> Org-Mode is not as uncommon as it might seem. GitHub accepts it and fully parses them.

In the Nextcloud ecosystem it *is* uncommon. I don't know a single Nextcloud app which provides support for it. Supporting `org` in terms of rendering was never a topic though, as i [stated above](https://github.com/nextcloud/notes/issues/722#issuecomment-847814408) for [the reasons i wrote at the help forum](https://help.nextcloud.com/t/writing-notes-in-org-mode/116993/2?u=stefan-niedermann):

> the focus of the Notes app is to provide a distraction free Markdown editor. Considering the limited resources of this community driven app, the fact that Markdown is the “de facto” standard in the Nextcloud eco system (supported by Nextcloud, Tasks, Deck, Notes and many others) and keeping in mind that an editor for org-mode needs to be adjusted to the same look and feel as the Markdown editor

The [proposed solution](https://github.com/nextcloud/notes/issues/722#issuecomment-849043770) seemed to allow us to have the cake and eat it: You could allow `.org` as extension and the overall usability would not suffer in the default configuration.
If this solution ain't sufficient for you though (because you are not an administrator), i [vote for keeping the state as it is](https://github.com/nextcloud/notes/issues/722#issuecomment-849348295). @korelstar you are the maintainer, it's your decision. If you are unsure, we can also ping the `nextcloud/designers` group for their opinion.

**Comment by korelstar** [comment]
> If this solution ain't sufficient for you though (because you are not an administrator), i [vote for keeping the state as it is](https://github.com/nextcloud/notes/issues/722#issuecomment-849348295). @korelstar you are the maintainer, it's your decision. If you are unsure, we can also ping the `nextcloud/designers` group for their opinion.

Yes, let's involve @nextcloud/designers regarding this question. Any opinions from you people?

**Comment by vincowl** [comment]
Hi,
As an org writer, I would have love to find a nextcloud app to write in org mode directly. But since Notes includes a markdown parser, I can't see the point to adding .org extension to notes. This costs me to state this since org and Notes are both really cool "tools"...

@pprevos  could you please describe the editing workflow you have in mind  ? I mean from creating to editing / modifying / using / searching... If you need tagging, you can do it in Files. You can mount nextcloud folders using webdavs, get ssh access, even probably use emacs' tramp mode to edit your org files remotely. That's why I decided to leave Notes to Markdown and use standard nextcloud features to use it with org and emacs.

Hope it helps...

**Comment by pprevos** [comment]
@vincowl My workflow is that I collect fleeting notes on the NexCloud mobile application, or in the browser when I am not on my computer. I can see the Org mode files already in my notes folder, but I cannot create new Org files from within NextCloud.

My suggestion is that I can change the file extension for new notes to .org (currently only includes .md or .txt). I think my question got a bit off the rails by using the word "default". No need for a changes for all users or a parser, just the org ile extension in the dropdown menu.

**Comment by vincowl** [comment]
@pprevos Here is how I process to do so in Nextcloud mobile app.

Add a file :
![20210919_104713.jpg](https://user-images.githubusercontent.com/16786457/133921314-a0675ffc-4de2-4606-9abc-9b5233189de9.jpg)

Choose to create a new text file (sorry, the menu is in french) :
![20210919_104648.jpg](https://user-images.githubusercontent.com/16786457/133921338-d540d1f3-87af-41ae-a941-0ab951d55593.jpg)

Change the whole name including the extension :
![20210919_104620.jpg](https://user-images.githubusercontent.com/16786457/133921358-319d166b-aac9-49e4-92e4-8e5a222ced5f.jpg)

You also could use `orgzly` linking to your Nextcloud instance using webdavs and automatically create and edit org notes

Would that help if designers reject this improvement request ?

**Comment by pprevos** [comment]
I thought the ticket would have been closed long ago.

I still don't understand why it is so hard to add .org as an extension to the dropdown list, but alas. We already spend too much energy on such a small request.

Thanks for your time

Peter

**Comment by PixsaOJ** [comment]
This sucks, Anyone can put bounty on this?

**Comment by vincowl** [comment]
> This sucks, Anyone can put bounty on this?

I can submit a PR to add .org to the dropdown menu. 
But I think the debate was not just as simple as this, but more something more philosophical, like "if we do this, won't it lead to add a ton of other custom extensions, so why not add custom extensions in a config section managed by an administrator ?". And this is a more complex job, maybe not fitting your workflow. A submitted PR may help to end this debate. I'll do it this evening if nobody is faster than me.

**Comment by PixsaOJ** [comment]
@vincowl Thing is about simplicity. Like, if people want to add more complex things or ask more complex things, that's on them. You don't have to do it, and maintainers have no liability whatsoever to do it.

But, this is a real simple thing and actually quite related to the project. Some people like to write in Text, some in Markdown and some power users who actually setup Nextcloud for their home cloud solution, they might prefer org  extension.

Use case would be to create a small note and save it. After, they come back at night and there is a synced note on their desktop. They continue writing in org-mode on their machines.

**Comment by vincowl** [comment]
@PixsaOJ I agree. But I am not a maintainer, and think that if a small contribution can make the maintainers decisions easier, it is worth it. 

But on the other hand, it is their responsibility to make their product easy to maintain and answer to a specific perimeter. Ways to handle things in private companies may not be the same on free open source projects maintained on personal time.

Even if I would love to write org files or use notes in a way which isn't the main one, I also understand that :
- notes may be used to write and handle markdown files only and that maintainers chose to stick to this.
- they don't want to add an extension even if it is tricky to do, because if they do so, where would it end ? Write xml, asciidoc, Tex, plantuml, css, js files or whatever ? It is their responsibility to foresee evolutions and this request may be handled wider than just .org files extension. That's why they talked about a different solution than just an addition to the dropdown menu and create a possibility to let the end user manage its extensions in a config file or in a config section for example. It should become a new feature and not a way to hack a project not initially thought the way we would have loved.

So, submitting a PR is just making a step towards them and reopen a debate that has been closed due to a lack of arguments and motivated developers to take this request into account. It is not a way to force them to accept this solution.
