### ISSUE TITLE
support for attachments / images [$106]

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/notes#74]
It would be nice to have some kind of attachment support to add an image or another file to a note

---
BountySource is no longer directly supported or endorsed by this repository. See #547 for more information. There is, however, an existing [$136 open bounty](https://www.bountysource.com/issues/43586252-support-for-attachments-images) on this issue.

**Comment by stefan-niedermann** [comment]
If the markdown renderer would support `[image](url)`-format, one could upload an image via drag and drop. The file gets a UUID as name and will be stored in the same folder where the corresponding note file is. After a successfull upload, the notes app can create the markdown with `[original-filename-without-extension](generated-uuid.extension)` and the image gets rendered.

**Comment by eemantsal** [comment]
Any news? Nowadays we take notes with much more content than just text, especially since we all have mobile devices with cameras. I think is a rather basic feature.
There's a desktop application for creating MD notes, Qownnotes, that creates a file named "Media" inside the folder of the note and saves there all the pictures we embed; then, in the note, there's just a link to the corresponding file in that "Media" folder. Seems rather uncomplicated (from a non programmer point of view, heheh).

**Comment by eemantsal** [comment]
The other day I was reading the issues of this application and saw [here](https://github.com/nextcloud/notes/issues/90#issuecomment-299860714) that @stefan-niedermann said that the server app was lacking an API that would add media support for the mobile app.
I thought Hr. Niedermann was referring to the Nextxloud server app, so [there I went to bother NC developers](https://github.com/nextcloud/server/issues/6768) to ask them for media support. @nickvergessen kindly clarified my confusion telling me that is was an NC Notes app issue, not an NC server's, so, here I'm back.

Since I see that @korelstar has already taken this issue into account I'd like to comment an idea from @jancborchardt that he's taken from the IOS app iA Writer, an idea to be considered once NC Notes web app will support media content, of course.
The normal procedure to insert, for example, an image in a Markdown note would be using `![Alt text](image_url)`, but as Mr. Borchardt comments about iA Writer, said app saves all the attached files in the same folder than the .md files, and you just have to type a sort of path to the attached filename preceded, something like `/image.png` (no dot before the slash, just the slash) and here you go.
I commented to him that the idea is nice, but would be better with a variant: To me, having all the media files mixed up in the same folder of the .md files can become a real mess if you have many notes with a few images each and need to do some file browsing in your notes folders. I prefer the storing structure that [Qownnotes](https://github.com/pbek/QOwnNotes) follows: it creates a folder named Media inside each notes folder, and then it stores all the multimedia content there, so, when you browse through your notes folders, yu see all your MD files together, and if want to open or edit any, there you have them clearly at your sight, and then you have said Media folder with all the pictures and such appart, wich seems clearer and more organized to me.
I think that if the app could read `/filename`and "translate" internally to `media/filename` it could display the attachments for each note withouth making our notes folders a messy "dump" for text files, images, audios... whatever, and at the same time keep that easy syntax.

In any case, whatever is the file storing model, I'm with Mr. Borchardt that the `/filename`thing is much handier than the habitual MD tag. I hope you may consider it.

Regards.

**Comment by jancborchardt** [comment]
Yep, can only repeat what @eemantsal mentioned about iA writer. They use the `/filename.png` syntax to directly integrate images from the same folder (or subfolders).

**Comment by Spartachetto** [comment]
I understand that my habits are different, yet usually I do **NOT** keep my images and file s in the same folder of my notes.

So for me it would be good to have the possibility to refer to any file stored in my Nextcloud instance via a simple syntax.

A big usability bonus woild be a tooltip that helps generating the syntax (a file selector that provides ad output the right syntax).

Two further improvements:
- autocomplection that proposes the previously used path when I use the syntax to cite a file a second time in a single note
- a way for the app to memorize the last used path for that note; in this way if I reopen the note and reuse the file picker, I get the  previously used path as a  suggestion

**Comment by jancborchardt** [comment]
@Spartachetto development always needs to happen in small steps. :) And the first step is as we describe. Supporting images which are somewhere else is something for a further step.

And an image outside of your Notes folder could for example be referred like
```
![](../Pictures/hedgehog.jpg)
```
And combined with the #200 context-based formatting popover we can have a filepicker for inserting images. :)

But all with time – and resources. Any contribution is welcome, or donations on Bountysource towards the issues: https://www.bountysource.com/issues/43586252-support-for-attachments-images

**Comment by Larsene** [comment]
Contribution to bountysource done. thanks for this app, and as said, an images/attachement features would be great :-)

**Comment by TobiasDev** [comment]
Are there any updates for this? Eg. can I somehow add images to a note that gets updated to something like a "resource" folder or such within notes?

**Comment by korelstar** [comment]
No, sorry. No progress seen.

**Comment by Larsene** [comment]
what a pity ! i'll increase the bounty on it...

**Comment by iSpeeX** [comment]
To be sure, it's a nearly basic feature noawadays for note taking apps. Thanks to the Nextckloud structure, as everybody said before, we could integrate any file. But the truth is that the most important are images.

**Comment by stefan-niedermann** [comment]
@SpeeX you can contribute by starting a Pull Request or increasing the bounty if you are not a developer. Please note, that a rewrite is currently done to VueJS in a branch if you want to create a PR :rocket:

**Comment by jcgerhard** [comment]
Hello Devs and Users,
are there any news on this feature? The only thing that prevents me and my collegues to use the notes app is the lack of image and attachement support!
This is absolutely mandatory for a modern note-taking tool. Im my case, we need to document technical workflows that need a lot of screenshots. So...PLEASE...add image support to the notes app!

**Comment by avuton** [comment]
If you're going to complain about the lack of this feature, please do us all a favor and put your money where your mouth is (add to the bounty). Asking for features to be implemented over and over is not a developer motivator.

**Comment by TobiasDev** [comment]
Is it possible to add this issue to IssueHunt? I already have money attached there and sadly can´t move them to bountysource. :( I understand if you don´t want two different places for this, just figured I´d ask.

**Comment by korelstar** [comment]
The link to bountysource was configured by @jospoortvliet. Maybe he can help?

I have no experiences with IssueHunt, but may be you can create the issue and post a bounty over there, too. We could link this from here.

**Comment by boistordu** [comment]
so how much do we need to add as money for a general media feature? Since when we need to be as precised as a photo. 
Can we specify which step would be smaller between :
1/ add a reference link like someone asked but which would require the use of a external tool most probably to get the image to print it to the screen 
2/ add the possibility to just upload the file in the same directory where the note is store and which would be whatever media or attachments. And then the responsability to open this attachment would be tied to the client of the API which can be a mobile app, a webbrowser or whatever it can be?

Because now we have 106$ for this feature but we clearly don't know which form it would take and I'm ready to wire whatever money it is necessary to make this thing happen after how much? 3 years of discussion.

**Comment by korelstar** [comment]
For the server/web app (this repository), this will be fixed by implementing #331, since the "Text" editor already supports images (for open issues regarding this feature see the "Text" repository).

However, we will have to add some functionality to the API for 3rd party apps. Here, we have to think about which way for saving images/attachments should be supported. Currently, there are two ways of inserting images using the "Text" app:

1. Insertion using the image button from the toolbar: you can chose an image from your Nextcloud and a link to that file is inserted. That link uses the preview functionality.
2. Paste an image from the clipboard directly to the text using CTRL+V: the image content is directly inserted into the note file (base64 encoded). This increases the note's file size heavily.

Manual insertion of image links with relative paths is not supported, yet.

I think we have to put up with what the Text app provides or create new issues/PR for the "Text" app if this is not sufficient.

For this app, we would have to implement a good API that supports all available types of image integrations. I think it would be best if images would be transferred on a separate stream to (mobile) clients in order to keep text synchronization fast. But the technical details have to be defined/discussed.

**Comment by frankgerhardt** [comment]
> Manual insertion of image links with relative paths is not supported, yet.

I can't even link/embed an image in the same directory as the note? I'm giving up. I thought making links is the deal breaker but not being able to embed images is it.

**Comment by CongAn** [comment]
I hope someone will develop it.

**Comment by lyallp** [comment]
I can insert an Image using existing notes app but it is a bit fiddly.

`![Media/Thunderbird-CardBook-AddressBook-Properties-DisplayName.PNG](/core/preview?fileId=54462&x=1536&y=864&a=true)`

I retrieved the URL using the Files App, right clicking the image and copy/paste the URL after the domain and using that as my URL in the note. 

Tedious but if you **really** want insert image functionality, this workaround should do.

**Comment by rca** [comment]
I'm on a Mac and am looking to see if nextcloud is a viable alternative to Apple's suite of tools; in this case the Notes app.

For this particular issue, when taking notes in Apple's notes app I can take a screenshot that gets cached in the clipboard and paste it into the note using the `cmd+v` shortcut.  In my opinion, this is the usability level to strive for when considering this feature.

I understand there are potential workarounds, but I presume it's the case for most people that they simply want to jot a thought down before it disappears, and while markdown* is great, for this use-case it gets in the way.
Thanks.

* I am a huge fan of notes being markdown, so don't take this comment out of context.  I really like the ability to use markdown, but I am also used to very intuitive apps in the same space.

**Comment by Metagit** [comment]
Is there any news about an option to insert pictures? It seems people are asking for that feature since 2017... I am really trying to degooglify my life and regain control over my data without becoming an apple user but things like this are killing me.
I just paid 3€ for this app, which is of course nothing. You guys deserve much more. But still: beeing able to attach pictures to a note is an absolute must in 2021. Otherwise, very very unfortunately, this app is basically not an option... :(
Is there a way to get notified once it supports images / attachments? I really want to use it as part of my nextcloud suite.

**Comment by 1989gironimo** [comment]
> Is there any news about an option to insert pictures? It seems people are asking for that feature since 2017... I am really trying to degooglify my life and regain control over my data without becoming an apple user but things like this are killing me.
> I just paid 3€ for this app, which is of course nothing. You guys deserve much more. But still: beeing able to attach pictures to a note is an absolute must in 2021. Otherwise, very very unfortunately, this app is basically not an option... :(
> Is there a way to get notified once it supports images / attachments? I really want to use it as part of my nextcloud suite.

You can simply subscribe to this issue and get notified if it has been closed.

**Comment by stefan-niedermann** [comment]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Commenting without providing new information will slow down the development because this kind of issues are hard to read and understand.

> I just paid 3€ for this app, which is of course nothing. You guys deserve much more.

That's wrong. You paid for the [Android client](https://github.com/stefan-niedermann/nextcloud-notes/issues) and not for this app. Thank you for the rating by the way, always appreciate this kind of communication. Always motivating.

> Is there a way to get notified once it supports images / attachments?

Yes, you can subscribe to GitHub issues (also without commenting). So you will get notified automatically now. You also can watch the [changelog](https://github.com/nextcloud/notes/blob/master/CHANGELOG.md)

**Comment by Metagit** [comment]
> You can simply subscribe to this issue and get notified if it has been closed.
True, thanks! But I don't think it is going to happen within a foreseeable time frame. Same as the password features/apps. I'm pretty sad that all of this is not actually a viable alternative without sacrificing tons of efficiency. Sorry for crying about this in here. I know it is the wrong place but I'm quite frustrated.

**Comment by Metagit** [comment]
> 
> That's wrong. You paid for the [Android client](https://github.com/stefan-niedermann/nextcloud-notes/issues) and not for this app. Thank you for the rating by the way, always appreciate this kind of communication. Always motivating.
> 

Sorry man. I'm just pretty frustrated that pretty much every nextcloud app has major flaws / downsides like this and therefore are simply not a viable options for daily use. I actually felt bad for leaving that rating because I don't want to be ungrateful nor disrespectful but at least it could prevent people from buying it and then having to ditch it because of the same reason.

By the way: I will try to mark my own comment here as off-topic due to the fact that what you said absolutely makes sense.

**Comment by elsiehupp** [comment]
I accidentally created a [duplicate issue](https://github.com/nextcloud/notes/issues/696), so here's the text of it copied-and-pasted over, with some light editing to make it more relevant here.

### Is your feature request related to a problem? Please describe.
I currently use Evernote. I would like to be able to escape from Evernote. One of my main use cases for Evernote is notes with managed attachments. While Nextcloud Notes does allow for attachments, said attachments much reside at publicly accessible URLs, which makes them brittle, and also doesn't allow for using Nextcloud Notes as a place to store attachments. I would rather not have to think about where the attachments are stored.

### Describe the solution you'd like
(This bit is probably largely redundant with other people's comments.) Nextcloud Notes could allow attachments to be stored in, say, a subfolder of the Notes folder, which would be hidden in the Notes UI. Nextcloud Notes would allow attachments to be uploaded through the web interface, and it would automatically copy attachments added from elsewhere in the user's Nextcloud drive. It would also keep track of orphaned attachments and move them to a trash-collection folder to be deleted after a certain period of time.

### Describe alternatives you've considered
The main alternative is using Joplin, which manages attachments, but Joplin doesn't integrate with Nextcloud beyond using it as a WebDAV server. I've looked into using QOwnNotes, but the user interface was a bit overwhelming, and it seemed like it was less suited to migration from Evernote.

### Additional context
It would be preferable for the attachment-management system to be relatively compatible with other Markdown solutions. For this reason, it may be worthwhile to copy the way Joplin or QOwnNotes manages attachments. Even better, Nextcloud Notes could support directly rendering the sync folder of one or both of these applications (which would take some pressure off of the first-party sync clients).

**Comment by stefan-niedermann** [comment]
@elsiehupp I collapsed your comment (no offense) because this issue is already quite crowded and the proposed solution is what i already suggested in my [first comment](https://github.com/nextcloud/notes/issues/74#issuecomment-290219121).

> I just added $15 to the bounty.

Please read the pinned issue "[Don’t use bountysource anymore! ](https://github.com/nextcloud/notes/issues/547)". @korelstar maybe you should remove the bounty sums from the issue titles.

**Comment by elsiehupp** [comment]
> Please read the pinned issue "[Don’t use bountysource anymore! ](https://github.com/nextcloud/notes/issues/547)". @korelstar maybe you should remove the bounty sums from the issue titles.

Now that you mention it, I do remember seeing that pinned issue, but I didn't click through to it. Should someone maybe go through and edit the `<bountysource-plugin>` section in each Issue to explain the situation? I mean, I have write access to do so myself, but I don't want to step on your toes here... I see [someone suggested removing the sections entirely](https://github.com/nextcloud/notes/issues/547#issuecomment-678656362), but it does seem useful to leave up the bounties that still exist.

Anyway, should I cancel my bounty? Or should I leave it up? 

I'll collapse my own comment here, and the last little bit in my longer comment I think I'll repost on its own, since it wasn't redundant with your comment.

**Comment by elsiehupp** [comment]
Several people have mentioned borrowing strategies from other Markdown solutions, but it might be preferable to choose one with which to develop and maintain actual cross-compatibility. That is, it could be nice if Nextcloud Notes supported using the sync folder of Joplin or QOwnNotes as a backend, specifically in the context of file attachments.

Something else to add is that one route to implementing this might be borrowing from Joplin's codebase, since Joplin is written largely in JavaScript and TypeScript, which overlaps with Nextcloud Notes' use of JavaScript (but not its use of PHP).

I added $15 to the bounty, but apparently we're not supposed to be using that anymore...

**Comment by referi** [comment]
Is there any progress of seeing images in notes?

**Comment by stefan-niedermann** [comment]
@referi The Notes Android app is able to display images in the preview mode since [`v3.4.6`](https://github.com/stefan-niedermann/nextcloud-notes/releases/tag/v3.4.6). Obviously, handling attachment is not yet implemented in the Notes server app (bevause otherwise this issue would have been closed). Please avoid spamming all subscribers of this issue with "me too" posts if you have nothing to contribute. Use

**Comment by reos-rcrozier** [comment]
Image viewing works in the Collectives app, which also displays markdown files, perhaps there is something useful to be seen there?

**Comment by newhinton** [comment]
@stefan-niedermann I started working on this issue. For now i am in the experimental stage, but my general approach is the following:

Serverside:
Creating two new api endpoints. 
1. Image/File fetching
2. Image/File uploading

Clientside:
3. Rewrite relative path's in `![alttext](relativeurl)` to link to the new api in **preview** mode
4. Add a button that allows to upload a file **next** to the current note.


Generally, as long as the relative path resolves to a valid file accessible by the user, the api will deliver that file.
Notes basically act's as a proxy to translate a relative path to an absolute url readable by the frontend.

So far i got 1. working, and the next goal is 3.
Is there a "good" way to do it, or should i abuse [linkify](https://github.com/markdown-it/linkify-it#example-2-add-twitter-mentions-handler) to rewrite the markdown for display?

**Comment by stefan-niedermann** [comment]
*Awesome*! Maybe you can create a draft Pull Request so we can discuss the details with a watch on the code?

(Btw i am not a developer of the server app, but i am sure @korelstar is watching this issue as well)

**Comment by newhinton** [comment]
Oh! I must have assumed you were involved aswell since you did the android app, but hey :D

I opened a pull request, but it is barely functional. But i think it get's the general idea across

**Comment by newhinton** [comment]
I have now completed my base implementation. All features work, the user can upload an image and the server.

**Comment by fazlerabbi37** [comment]
@newhinton linking the server and client PR's in this issue would be very helpful. :smile:

**Comment by newhinton** [comment]
Sure! This is the server PR: #785 (Which is already working!)
And here is the android issue: https://github.com/stefan-niedermann/nextcloud-notes/issues/1051 
The android app has no implementation though, it's just how it could be extended
