### ISSUE TITLE
Changing UI language doesn't rename the "Notes" folder

### ISSUE THREAD

**Issue by k-bx** [nextcloud/notes#815]
Nextcloud is creating a folder named in whichever UI language chosen, which was Ukrainian for me, so it names the folder "Нотатки". After switching to English UI it's still named "Нотатки". My proposal would be not not use localised folder names, as it will lead to many problems like this everywhere, Ubuntu had previously done that decision and still has bugs in it every time you change language, things just break at random places. I would rather recommend using English and making localised symlinks or just sticking to English altogether.

**Comment by korelstar** [comment]
This behavior is intended. Please see #486 and #557 for more information. For people who use the correct locale from beginning, this feature works as intended. Those few people who change their locale after using the notes app for the first time, they can rename the notes folder using the files app and then use the notes app settings (bottom left corner) for changing the notes folder to the renamed folder. I assume that changing a locale won't happen very often. Therefore, this workaround is arguable.

I really don't want to rename the notes folder automatically on every locale change, since this would really likely break many things.

**Comment by korelstar** [comment]
No problem. As stated above, you will have to do the following two steps:

- Open notes app, open app settings (it's in the lower left corner). There you set the notes path to `Notes`.
- Open Nextcloud files app, move all your notes files from the old folder to the new Notes folder.
