### ISSUE TITLE
Change the date of notes

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [nextcloud/notes#866]
**Is your feature request related to a problem? Please describe.**
I'd like to import my notes from another notes app, and I would also like the dates of these notes to be maintained. So, my notes from 2020 show up as being last modified in 2020 in Nextcloud notes.

**Describe the solution you'd like**
Allow us to choose the creation date of notes.

**Additional context**
In the current state, my notes from 2020 show up as just being created today, making looking through my notes confusing, so I still have to keep my old note app to check the dates.

**Comment by korelstar** [comment]
How do you import your old notes? If you have your old notes as files with the old modified time, you can import them using the Nextcloud files app or using the Nextcloud desktop app. In these cases, the modified time will be preserved.

Since this scenario is an edge case, I don't think we should add the functionality directly in the notes app. Please give feedback if the above workaround did helped!

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I haven't imported them yet, but I'm coming from Standard Notes. I was planning on copy and pasting each note, but the dates won't be included in the Nextcloud version.

Perhaps recognizing creation dates and modified dates alongside the feature of altering these dates would make my suggestion more useful.

> this scenario is an edge case
To people using Nextcloud notes already I see few using this feature, but to users switching it's important, to me at least. I've only used the email import feature to copy my emails to my current provider once for example, but without it I'd be in a pickle.

**Comment by korelstar** [comment]
Sorry for my late reply.

As I said, you are already able to import notes files while preserving the modified time of that files. The question is: in which format do you are able to export notes from your old notes software? Shouldn't that software provide an export that preserves the modified time?

Since there are countless notes apps in the world that store notes in very different formats, we cannot provide import functionality for all of them. Therefore, the approach of the notes app is to reduce to the simplest approach: simple text files. I think this is a sufficient interface for importing notes.
