### ISSUE TITLE
Sync Compatibility with the quillnote app

### ISSUE THREAD

**Issue by talesam** [nextcloud/notes#904]
The best app I've found for android that has a certain sync with Nextcloud is quillnote, but the notes don't have a good sync like in the app, it could have better compatibility, the app is amazing and full of features. Until the last time I tested, the notes were only synced in the app, but not with the nextcloud server.

https://github.com/msoultanidis/quillnote

**Comment by korelstar** [comment]
The notes app provides a [public API](https://github.com/nextcloud/notes/blob/master/docs/api/README.md) for third-party apps. It looks like quillnote implements parts of that API, but it does not work correctly: https://github.com/msoultanidis/quillnote/issues/179 . This issue is open since several months. There is already a PR that may fix this issue: https://github.com/msoultanidis/quillnote/pull/199

However, bugfixing has to be done in quillnote - there is nothing we can do in the notes app regarding this. In the meanwhile, you could try another [Android app](https://github.com/stefan-niedermann/nextcloud-notes) - here, synchronization to Nextcloud Notes using that API works perfectly.
