### ISSUE TITLE
Paste/dragdrop images

### ISSUE THREAD

**Issue by aPollO2k** [nextcloud/notes#918]
It should be possible to paste/dragdrop images directly into a note without the need of save the image as file on disk and upload manually.

**Comment by stefan-niedermann** [comment]
I agree, maybe you want to start a Pull Request for this? :rocket:

**Comment by demuxer86** [comment]
The only reason I can't use this app is because I can't add pictures to the notes from my android phone.   It's a key feature to any note app imo.    Taking a picture of something, being able to do basic drawings on that picture, and then adding some text to the note.   That's invaluable and Google Keep is the only note app that does it mostly right.

**Comment by stefan-niedermann** [comment]
@demuxer86 your feature request is not related to this issue. The Notes Android app [is waiting for an external API for attachments](https://github.com/nextcloud/notes/issues/826) and will implement support for adding attachments when it is available. Please use GitHub reactions (👍) in the future when you are affected by an issue and have no new information to add. Thank you.
